### ISSUE TITLE
restart_app() causes invalid thread ID

### ISSUE THREAD

**Issue by danhei** [AppDaemon/appdaemon#1025]
My app is pinned to a thread (e.g. 29). When the app is restarted with the function restart_app(<name>) it will be restarted, but is no longer pinned to this thread (it gets thread ID -1). And if this app has some callbacks, this causes error `Invalid thread ID for pinned thread`.

Example:
#### apps.yaml
```yaml
app_a:
  module: app_a
  class: AppA

app_b:
  module: app_b
  class: AppB
```

#### app_a.py
```python
import hassapi as hass

class AppA(hass.Hass):
    def initialize(self):
        self.log(f"pin={self.get_pin_thread()}")
        self.work()

    def work(self, kwargs={}):
        self.log(f"work  pin={self.get_pin_thread()}")
        self.run_in(self.work, delay=1)
```

#### app_b.py
```python
import hassapi as hass

class AppB(hass.Hass):
    def initialize(self):
        self.log(f"pin={self.get_pin_thread()}")
        self.run_in(self.delayed, delay=10)

    def delayed(self, kwargs):
        name = "app_a"
        self.log(f"restart app '{name}'")
        self.restart_app(name)
```

#### log file
```log
2020-08-14 10:48:34.681521 INFO AppDaemon: Initializing app app_a using class AppA from module app_a
2020-08-14 10:48:34.684003 INFO AppDaemon: Initializing app app_b using class AppB from module app_b
2020-08-14 10:48:34.700706 INFO app_a: pin=29
2020-08-14 10:48:34.707760 INFO app_a: work  pin=29
2020-08-14 10:48:34.725974 INFO app_b: pin=30
2020-08-14 10:48:36.037164 INFO app_a: work  pin=29
2020-08-14 10:48:37.009335 INFO app_a: work  pin=29
2020-08-14 10:48:38.028886 INFO app_a: work  pin=29
2020-08-14 10:48:39.028525 INFO app_a: work  pin=29
2020-08-14 10:48:40.039853 INFO app_a: work  pin=29
2020-08-14 10:48:41.037348 INFO app_a: work  pin=29
2020-08-14 10:48:42.045664 INFO app_a: work  pin=29
2020-08-14 10:48:43.034264 INFO app_a: work  pin=29
2020-08-14 10:48:44.020293 INFO app_a: work  pin=29
2020-08-14 10:48:45.023657 INFO app_b: restart app 'app_a'
2020-08-14 10:48:45.027552 INFO AppDaemon: Terminating app_a
2020-08-14 10:48:45.028526 INFO AppDaemon: Initializing app app_a using class AppA from module app_a
2020-08-14 10:48:45.068134 INFO app_a: pin=-1
2020-08-14 10:48:45.086081 INFO app_a: work  pin=-1
2020-08-14 10:48:46.004478 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:46.023165 INFO app_a: work  pin=-1
2020-08-14 10:48:47.010430 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:47.021233 INFO app_a: work  pin=-1
2020-08-14 10:48:48.007721 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:48.034225 INFO app_a: work  pin=-1
2020-08-14 10:48:49.004995 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:49.038659 INFO app_a: work  pin=-1
2020-08-14 10:48:50.007245 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:50.125093 INFO app_a: work  pin=-1
2020-08-14 10:48:51.004402 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:51.034333 INFO app_a: work  pin=-1
2020-08-14 10:48:52.009446 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:52.048131 INFO app_a: work  pin=-1
2020-08-14 10:48:53.005270 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:53.036866 INFO app_a: work  pin=-1
2020-08-14 10:48:54.003656 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:54.021207 INFO app_a: work  pin=-1
2020-08-14 10:48:55.000965 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:55.014545 INFO app_a: work  pin=-1
2020-08-14 10:48:56.007265 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:56.048261 INFO app_a: work  pin=-1
2020-08-14 10:48:57.003539 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:57.016649 INFO app_a: work  pin=-1
2020-08-14 10:48:58.009284 WARNING AppDaemon: Invalid thread ID for pinned thread in app: app_a - assigning to thread 0
2020-08-14 10:48:58.042676 INFO app_a: work  pin=-1
```

When that app is restarted because a .yaml or .py file is changed (disabled production mode), the app is pinned to the same thread again and everything works fine. Should the function `self.restart_app(<name>)` not have the same behavior?

**Comment by Odianosen25** [comment]
@danhei thats interesting, it should have the same behaviour. Never noticed it, though I use mostly the service call. Can you try using the service call, and see if it’s the same issue please?

self.call_service(“app/restart”, app=“app_a”)

**Comment by danhei** [comment]
The service has the same behavior.

And sometimes I get an additional error (with call_service and restart_app):
```
2020-08-14 12:41:22.047387 WARNING app_a: Unexpected error in worker for App app_a:
2020-08-14 12:41:22.048165 WARNING app_a: Worker Ags: {'id': '0f28cf97b4f74382b60bd7665ada5160', 'name': 'app_a', 'objectid': '673ecac86f4848fb8b39a99e51208f64', 'type': 'scheduler', 'function': <bound method AppA.work of <app_a.AppA object at 0x7f94dc1a8f28>>, 'pin_app': True, 'pin_thread': 29, 'kwargs': {'__thread_id': 'thread-29'}}
2020-08-14 12:41:22.048690 WARNING app_a: ------------------------------------------------------------
2020-08-14 12:41:22.049787 WARNING app_a: Traceback (most recent call last):
  File "/home/username/appdaemon/lib/python3.7/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/home/username/.homeassistant/conf/apps/_test/restart_test/app_a.py", line 11, in work
    self.run_in(self.work, delay=1)
  File "/home/username/appdaemon/lib/python3.7/site-packages/appdaemon/utils.py", line 195, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/home/username/appdaemon/lib/python3.7/site-packages/appdaemon/utils.py", line 299, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/username/appdaemon/lib/python3.7/site-packages/appdaemon/adapi.py", line 2168, in run_in
    handle = await self.AD.sched.insert_schedule(name, exec_time, callback, False, None, **kwargs)
  File "/home/username/appdaemon/lib/python3.7/site-packages/appdaemon/scheduler.py", line 295, in insert_schedule
    pin_app = self.AD.app_management.objects[name]["pin_app"]
KeyError: 'app_a'
```

**Comment by ReneTode** [comment]
odia, the difference could becaused because you use new style apps and danhei is using old style apps.

i suspect that you never tested this with old style apps, and that this is a bug.

**Comment by danhei** [comment]
What must be changed to make it a "new style" app?

**Comment by Odianosen25** [comment]
That's a good point @ReneTode 

@danhei do try this for app b

```
import adbase as ad

class AppB(ad.ADBase):
    def initialize(self):
        self.adapi = self.get_ad_api()
        self.adapi.log(f"pin={self.get_pin_thread()}")
        self.adapi.run_in(self.delayed, delay=10)

    def delayed(self, kwargs):
        name = "app_a"
        self.adapi.log(f"restart app '{name}'")
        self.adapi.restart_app(name)
```

**Comment by Odianosen25** [comment]
Ah I think I know the issue. When this api was added, my apps were pined and so doesn't cause an issue for me.
For non-pin environments, will be a pain as I didn't consider that.

Ok @danhei my above example wouldn't work,  so this will need fixing.

**Comment by danhei** [comment]
@Odianosen25 I use AppDaemons default configuration. That means the option`pin_apps` is true (default) and all apps are pinned. Therefore, I do not use a "non-pin environment". Or do you refer to something else?

**Comment by Odianosen25** [comment]
@danhei what I meant, was you not **manually pining** your apps, apologies for the mistake. Will put in a fix for it

**Comment by Odianosen25** [comment]
This is fixed
