### ISSUE TITLE
appdaemon code didn't work after Home Assistant update

### ISSUE THREAD

**Issue by tymzang** [AppDaemon/appdaemon#1058]
Hi everyone,

After I upgraded Home Assitant to 0.116.4 few days ago, my appdaemon code didn't work any more. Please help me to overcome the problem with below log:

=====================================

2020-10-24 16:02:35.634648 INFO AppDaemon: Initializing app count_day_1 using class Calendar from module calendar
2020-10-24 16:02:35.638333 WARNING count_day_1: ------------------------------------------------------------
2020-10-24 16:02:35.639508 WARNING count_day_1: Unexpected error initializing app: count_day_1:
2020-10-24 16:02:35.640604 WARNING count_day_1: ------------------------------------------------------------
2020-10-24 16:02:35.646838 WARNING count_day_1: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 907, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 294, in init_object
    "object": app_class(
TypeError: __init__() takes from 1 to 2 positional arguments but 8 were given
2020-10-24 16:02:35.647956 WARNING count_day_1: ------------------------------------------------------------
2020-10-24 16:02:35.649283 INFO AppDaemon: Initializing app count_day_2 using class Calendar from module calendar
2020-10-24 16:02:35.656482 WARNING count_day_2: ------------------------------------------------------------
2020-10-24 16:02:35.657684 WARNING count_day_2: Unexpected error initializing app: count_day_2:
2020-10-24 16:02:35.658852 WARNING count_day_2: ------------------------------------------------------------
2020-10-24 16:02:35.660456 WARNING count_day_2: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 907, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 294, in init_object
    "object": app_class(
TypeError: __init__() takes from 1 to 2 positional arguments but 8 were given
2020-10-24 16:02:35.661514 WARNING count_day_2: ------------------------------------------------------------
2020-10-24 16:02:35.662892 INFO AppDaemon: Initializing app count_day_4 using class Calendar from module calendar
2020-10-24 16:02:35.669402 WARNING count_day_4: ------------------------------------------------------------
2020-10-24 16:02:35.670618 WARNING count_day_4: Unexpected error initializing app: count_day_4:
2020-10-24 16:02:35.671696 WARNING count_day_4: ------------------------------------------------------------
2020-10-24 16:02:35.673271 WARNING count_day_4: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 907, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 294, in init_object
    "object": app_class(
TypeError: __init__() takes from 1 to 2 positional arguments but 8 were given
2020-10-24 16:02:35.674311 WARNING count_day_4: ------------------------------------------------------------
2020-10-24 16:02:35.677502 WARNING AppDaemon: Unable to find module count_day_1 - initialize() skipped
2020-10-24 16:02:35.679853 WARNING AppDaemon: Unable to find module count_day_2 - initialize() skipped
2020-10-24 16:02:35.682188 WARNING AppDaemon: Unable to find module count_day_4 - initialize() skipped
2020-10-24 16:02:35.684998 INFO AppDaemon: App initialization complete

**Comment by ReneTode** [comment]
hard to say what goes wrong without the app.

**Comment by Odianosen25** [comment]
@tymzang from the logs it seems your initialise function’s signature is wrong. Also it’s also possible using “calendar” which I believe is an internal python module on its own is messing stuffs up. But lastly as Rene said, without the app difficult to say what’s going on.

will be closing this issue, and kindly reopen if further issues found. Regards

**Comment by tymzang** [comment]
@ReneTode, @Odianosen25 

I just had temporary solution. When I restart Home Assistant, my appdaemon didn't work and shows log as you saw above. Then I just open my own python script calendar.py, don't do anything and save calendar.py. After that, appdaemon works fine. I think problem is located at "def initialize(self)", but I don't know exactly problem.

**Below is my shorten app. yaml and python script calendar.py**

##### ##### ##### #####  apps.yaml
---
lunar_date:
  module: calendar
  class: Calendar
  type: LichVanNien
count_day_1:
  module: calendar
  class: Calendar
  name: Sinh nhật tui
  type: DL
  date: 10/02

##### ##### ##### #####  calendar.py

import appdaemon.plugins.hass.hassapi as hass
import math
import datetime
from datetime import date
from datetime import timedelta
import re # For removing Vietn

amese accents 

"""
Count Day App

Arguments:

Lịch Vạn Niên
---type: LichVanNien #Lunar Date

Dương Lịch
---name: Nguyễn Văn A
---type: DL #Dương Lịch
---date: 25/09 (dd/mm)

Âm Lịch
---name: Nguyễn Văn A
---type: AL #Âm Lịch
---date: 25/09 (dd/mm)

"""
class Calendar(hass.Hass):
    
    def initialize(self):
        # The "ha_started" event has been renamed to "plugin_started"
        #self.listen_event(self.ha_event, "ha_started")
        
        # Create a time object for 00:00:30am
        runTime = datetime.time(0, 0, 30)
        # Schedule a daily call that will call count_down() at 00:00:30am every day
        self.run_daily(self.select_options, runTime)

        #self.select_options(self)
        delay = 0
        self.run_in(self.select_options, delay)
    
    # Run this after plug in started
    def ha_event(self, event_name, data, kwargs):
        delay = 30
        self.run_in(self.select_options, delay)

    # Choose which function to run    
    def select_options(self, kwargs):
        dateType = self.args["type"]
        if (dateType == "LichVanNien"):
            self.log("AppDaemon Lunar Date by Tym Zang")
            self.lunar_calendar(self)
        elif (dateType == "DL"):
            self.log("AppDaemon Count Solar Day by Tym Zang")
            self.count_solar_day(self)
        elif (dateType == "AL"):
            self.log("AppDaemon Count Lunar Day by Tym Zang")
            self.count_lunar_day(self)
        else:
            self.log("Please give corrected type for app {}".format(self.name))

**Comment by tymzang** [comment]
@ReneTode, @Odianosen25 

I just had temporary solution. When I restart Home Assistant, my appdaemon didn't work and shows log as you saw above. Then I just open my own python script calendar.py, don't do anything and save calendar.py. After that, appdaemon works fine. I think problem is located at "def initialize(self)", but I don't know exactly problem.

**Below is my shorten app. yaml and python script calendar.py**

**##### ##### ##### #####  apps.yaml**
lunar_date:
  module: calendar
  class: Calendar
  type: LichVanNien
count_day_1:
  module: calendar
  class: Calendar
  name: Sinh nhật tui
  type: DL
  date: 10/02

**##### ##### ##### #####  calendar.py**
import appdaemon.plugins.hass.hassapi as hass
import math
import datetime
from datetime import date
from datetime import timedelta
import re

class Calendar(hass.Hass):
    
    def initialize(self):
        # The "ha_started" event has been renamed to "plugin_started"
        #self.listen_event(self.ha_event, "ha_started")
        
        # Create a time object for 00:00:30am
        runTime = datetime.time(0, 0, 30)
        # Schedule a daily call that will call count_down() at 00:00:30am every day
        self.run_daily(self.select_options, runTime)

        #self.select_options(self)
        delay = 0
        self.run_in(self.select_options, delay)
    
    # Run this after plug in started
    def ha_event(self, event_name, data, kwargs):
        delay = 30
        self.run_in(self.select_options, delay)

    # Choose which function to run    
    def select_options(self, kwargs):
        dateType = self.args["type"]
        if (dateType == "LichVanNien"):
            self.log("AppDaemon Lunar Date by Tym Zang")
            self.lunar_calendar(self)
        elif (dateType == "DL"):
            self.log("AppDaemon Count Solar Day by Tym Zang")
            self.count_solar_day(self)
        elif (dateType == "AL"):
            self.log("AppDaemon Count Lunar Day by Tym Zang")
            self.count_lunar_day(self)
        else:
            self.log("Please give corrected type for app {}".format(self.name))

**Comment by Odianosen25** [comment]
Hello @tymzang,

change the name of the python script from calendar to something else.

regards

**Comment by ReneTode** [comment]
thats possible, but that doesnt explain why it works afterwards.
i dont think the same errors are there now, because i suspect there are changes made after that.

if changing the name doesnt help we will need to see the whole yaml and app.

**Comment by tymzang** [comment]
@Odianosen25, @ReneTode ... then give me more time to test my apps after change its name... I will try all possibilities of HA normal reboot, normal restart, reboot after OS upgrade, restart after OS upgrade, etc,...

**Comment by ReneTode** [comment]
there are only 2 interesting things:

restart HA without restarting AD and restarting AD after restart HA.
and you cant reboot HA. (unless you mean rebooting the device that has HA on it, which will restart HA and AD)

things like OS upgrade will only confuse.

**Comment by tymzang** [comment]
@ReneTode: I tried both options which you mentioned... so far so good after change **calendar.py** to **my_calendar.py**

@Odianosen25: Thanks for your suggestion... You can close this topic now... I will comment later if this issue still happen in next few months...
