### ISSUE TITLE
How to import class from different module with helper functions?

### ISSUE THREAD

**Issue by andreypolyak** [AppDaemon/appdaemon#1068]
I'm trying to move repeating code in many AppDaemon apps to helper module with common functions.

To do this I created ```helpers.py``` module with this code:

```python
import appdaemon.plugins.hass.hassapi as hass

class Helpers(hass.Hass):

  def initialize(self):
    self.some_value = 1

  def do_something(self, value):
    value += self.some_value
    return value
```

I also have my app (```my_app.py```) where I want to use my helpers function:

```python
import appdaemon.plugins.hass.hassapi as hass
from helpers import Helpers

class MyApp(hass.Hass):

  def initialize(self):
    self.helpers = Helpers()
    # do something using helpers
```

In my ```apps.yaml``` I has these two apps:

```yaml
global_modules:
  - helpers

my_app:
  module: my_app
  class: MyApp
  global_dependencies: helpers
```

Unfortunately, it doesn't work, I get this error:

```
2020-11-06 14:05:05.767932 WARNING my_app: ------------------------------------------------------------
2020-11-06 14:05:05.768294 WARNING my_app: Unexpected error in worker for App my_app:
2020-11-06 14:05:05.768623 WARNING my_app: Worker Ags: {}
2020-11-06 14:05:05.768924 WARNING my_app: ------------------------------------------------------------
2020-11-06 14:05:05.770474 WARNING my_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 150, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/global/my_app.py", line 9, in initialize
    self.persons = Persons()
TypeError: __init__() missing 7 required positional arguments: 'ad', 'name', 'logging', 'args', 'config', 'app_config', and 'global_vars'
2020-11-06 14:05:05.772674 WARNING my_app: ------------------------------------------------------------
```

What I did wrong?

Thanks in advance!

Andrey

**Comment by andreypolyak** [comment]
Ok, found the way to do it!

```my_app.py```:

```python
import appdaemon.plugins.hass.hassapi as hass
from helpers import Helpers

class MyApp(hass.Hass):

  def initialize(self):
    self.helpers = self.get_app("helpers")
    # do something using helpers
```

```apps.yaml```:

```yaml
helpers:
  module: helpers
  class: Helpers

my_app:
  module: my_app
  class: MyApp
  dependencies: helpers
```
