### ISSUE TITLE
Can't get notify to work using a async app

### ISSUE THREAD

**Issue by Hellowlol** [AppDaemon/appdaemon#1121]
```yaml
test_notify:
   module: test_notify
   class: TestNotifyAsync
```

```python
from datetime import timedelta
import hassapi as hass
class TestNotifyAsync(hass.Hass):
    async def initialize(self):
        now = await self.get_now()
        handle = await self.run_at(self.cb, now + timedelta(seconds=10))

    async def cb(self, **kwargs):
        await self.notify("TEST from TestNotifyAsync")
```
I get the traceback:
````
2021-01-17 20:46:29.006699 WARNING test_notify: Unexpected error in worker for App test_notify:
2021-01-17 20:46:29.007463 WARNING test_notify: Worker Ags: {'id': '5093409f0154422fb6ff46f0ee73ed0a', 'name': 'test_notify', 'objectid': '10a7103b1ba543cebba6cbd647a7d189', 'type': 'scheduler', 'function': <bound method TestNotifyAsync.cb of <test_notify.TestNotifyAsync object at 0x7ff2e63dbdf0>>, 'pin_app': True, 'pin_thread': 4, 'kwargs': {'__thread_id': 'MainThread'}}
2021-01-17 20:46:29.008187 WARNING test_notify: ------------------------------------------------------------
2021-01-17 20:46:29.009795 WARNING test_notify: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 798, in async_worker
    await funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/test_notify/test_notify.py", line 20, in cb
    await self.notify("TEST from TestNotifyAsync")
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 21, in func_wrapper
    plugin = utils.run_coroutine_threadsafe(self, self.AD.plugins.get_plugin_object(ns))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
2021-01-17 20:46:29.010562 WARNING test_notify: ------------------------------------------------------------
2021-01-17 20:46:29.012426 WARNING AppDaemon: callback cb() in test_notify has now completed
````

If i do the same with a normal app it works:

````
test_notify:
   module: test_notify
   class: TestNotifySync
````

```
class TestNotifySync(hass.Hass):
    def initialize(self):

        now = self.get_now()
        handle = self.run_at(self.cb, now + timedelta(seconds=10))

    def cb(self, **kwargs):
        self.notify("TEST from TestNotifySync")
```

What can I do to fix this?

**Comment by ReneTode** [comment]
try using call_service instead.

there are still a few convenience functions that are not working in async.
or just use sync apps, which would be my advise anyway.

**Comment by Hellowlol** [comment]
I can't the rest of the library is async. Thanks! That worked :)

**Comment by Hellowlol** [comment]
Reopening this as the the problem seems to happen on every method that is decorated with hass_check. Is the async interface to home assistant broken?

**Comment by ReneTode** [comment]
others use it, so i guess not.

just some of the convenience functions were not working.

**Comment by Odianosen25** [comment]
This issue should be fixed in the latest dev.

So will be closing now, and do re-open if any other thing.

Regards
