### ISSUE TITLE
cannot pickle '_thread.RLock' object crash 

### ISSUE THREAD

**Issue by hhaim** [AppDaemon/appdaemon#1414]
when moving from 3.x to 4.1.0 i get this error 
```
appdaemon        | 2021-12-09 20:38:18.867571 WARNING AppDaemon: ------------------------------------------------------------
appdaemon        | 2021-12-09 20:38:18.869352 INFO AppDaemon: Previous message repeated 1 times
appdaemon        | 2021-12-09 20:38:18.869469 WARNING AppDaemon: Unexpected error during process_event()
appdaemon        | 2021-12-09 20:38:18.869581 WARNING AppDaemon: ------------------------------------------------------------
appdaemon        | 2021-12-09 20:38:18.870011 WARNING AppDaemon: Traceback (most recent call last):
appdaemon        |   File "/usr/local/lib/python3.9/site-packages/appdaemon/events.py", line 245, in process_event
appdaemon        |     mydata = deepcopy(data)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
appdaemon        |     y[deepcopy(key, memo)] = deepcopy(value, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
appdaemon        |     y[deepcopy(key, memo)] = deepcopy(value, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
appdaemon        |     y[deepcopy(key, memo)] = deepcopy(value, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
appdaemon        |     y[deepcopy(key, memo)] = deepcopy(value, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)

   y = _reconstruct(x, memo, *rv)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 270, in _reconstruct
appdaemon        |     state = deepcopy(state, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
appdaemon        |     y = copier(x, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
appdaemon        |     y[deepcopy(key, memo)] = deepcopy(value, memo)
appdaemon        |   File "/usr/local/lib/python3.9/copy.py", line 161, in deepcopy
appdaemon        |     rv = reductor(4)
appdaemon        | TypeError: cannot pickle '_thread.RLock' object

```

**Comment by ReneTode** [comment]
sorry, but without more info its hard to tell what is going wrong.

**Comment by hhaim** [comment]
@ReneTode thanks for the quick response. I had in mind that this is a known issue. If a deepcopy added to the events kargs, this can explain this. 
I will try to track the specific application that trigger this in my case.

**Comment by hhaim** [comment]
@ReneTode upgrade back to 4.1.0 with no luck to reconstruction. Will close this for now. I assume this is one of my app that send to the event a complex object
