### ISSUE TITLE
run_corutine_threadsafe excepts wrong exception

### ISSUE THREAD

**Issue by tdobrovolny** [AppDaemon/appdaemon#1432]
Hello,

I came across this. When the tasks takes longer then the `internal_function_timeout` an exception from futures is raised `concurrent.futures._base.TimeoutError` instead of the excepted `asyncio.TimeoutError`.

https://github.com/AppDaemon/appdaemon/blob/f2c4649567df9caf5a671f0c47a08365e6ba85b6/appdaemon/utils.py#L316-L327

My log:
```
2021-12-26 10:55:12.004995 INFO AppDaemon: thread-2 calling scheduler callback _reevaluation_cb() in schedy_heating
2021-12-26 10:55:22.078975 WARNING schedy_heating: ------------------------------------------------------------
2021-12-26 10:55:22.079431 WARNING schedy_heating: Unexpected error in worker for App schedy_heating:
2021-12-26 10:55:22.079821 WARNING schedy_heating: Worker Ags: {'id': '64f12e25e7644dbfb0ddefe2ab884cde', 'name': 'schedy_heating', 'objectid': '5498da0efe734cc792b808e56691ec7d', 'type': 'scheduler', 'function': <function Room.trigger_reevaluation.<locals>._reevaluation_cb at 0x7efca72ade50>, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'thread-2'}}
2021-12-26 10:55:22.080187 WARNING schedy_heating: ------------------------------------------------------------
2021-12-26 10:55:22.081110 WARNING schedy_heating: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/threading.py", line 890, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/room.py", line 723, in _reevaluation_cb
    self.apply_schedule(reset=reset)
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/room.py", line 50, in wrapper
    result = handler(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/room.py", line 408, in apply_schedule
    self.set_value(new_scheduled_value, force_resend=force_resend)
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/room.py", line 587, in set_value
    changed |= actor.set_value(value, force_resend=force_resend)[0]
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/actor/base.py", line 285, in set_value
    self._resending_cb({"left_tries": self.cfg["send_retries"] + 1})
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/room.py", line 50, in wrapper
    result = handler(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/actor/base.py", line 93, in _resending_cb
    self.do_send()
  File "/usr/local/lib/python3.9/site-packages/hass_apps/schedy/actor/thermostat.py", line 323, in do_send
    self.app.call_service(
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 197, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 317, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 447, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

2021-12-26 10:55:22.081443 WARNING schedy_heating: ------------------------------------------------------------
2021-12-26 10:55:22.085514 INFO AppDaemon: thread-2 done
```

I'm not so familiar with this so not sure if the intention is indeed to wait for asyncio as there might be asyncio `wait_for` in the underlying corutine and in that case the code should except both or if it is there only for the `future.results` and in that case should be replaced with `concurrent.futures.TimeoutError` exception.

**Comment by Odianosen25** [comment]
@tdobrovolny,

I have read your issue several times, and apologies I don't seem to be able to understand what you are saying.

You asking we change what is being captured, and your view is that the wrong exception is being captured; as really looking at it seems to be the case

**Comment by tdobrovolny** [comment]
@Odianosen25 

No issues at all.

Yes that is the case.

The only thing is I don't know the project so well. So I don't know if the `concurrent.futures.TimeoutError` Exception should be added :
```python
try:
   ...
except (asyncio.TimeoutError, concurrent.futures.TimeoutError):
```

or just replaced:

```python
try:
   ...
except concurrent.futures.TimeoutError:
```

**Comment by Odianosen25** [comment]
@tdobrovolny,

This has been fixed in dev, so will be closing this issue.

Reopen if any other things needed.
