### ISSUE TITLE
Run_Every crashes appdaemon

### ISSUE THREAD

**Issue by meluvalli** [AppDaemon/appdaemon#1452]
Hello.  Have a VERY basic test script and if I launch it with "run_every", appdaemon crashes.  I have ran the same script with a listen_state and it works fine.  Maybe a bug or maybe I'm not using run_every correctly?  Wanting to run every 30 seconds.

Script:
<pre>
import appdaemon.plugins.hass.hassapi as hass
from datetime import datetime

class HelloWorld(hass.Hass):

    def initialize(self):
        self.log("Hello from AppDaemon")
        self.log("You are now ready to run Apps!")
        self.run_every(self.ForceClearZones(True), datetime.now(), 30)

    def ForceClearZones(self, bytime):
        self.log("Running ForceClearZones...")
        if bytime == True:
            self.log("ByTime = True")
        elif bytime == False:
            self.log("ByTime = False")
        else:
            self.log("Unknown ByTime Variable")
</pre>

Logs:
<pre>
2022-01-08 17:30:26.042467 INFO AppDaemon: Initializing app Test using class HelloWorld from module Test
2022-01-08 17:30:26.110445 INFO Test: Hello from AppDaemon
2022-01-08 17:30:26.111817 INFO Test: You are now ready to run Apps!
2022-01-08 17:30:26.112835 INFO Test: Running ForceClearZones...
2022-01-08 17:30:26.113858 INFO Test: ByTime = True
2022-01-08 17:30:26.117048 INFO AppDaemon: App initialization complete
Exception in thread thread-0:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 877, in worker
    callback = "{}() in {}".format(funcref.__name__, name)
AttributeError: 'NoneType' object has no attribute '__name__'
2022-01-08 17:30:56.556213 CRITICAL AppDaemon: Thread thread-0 has died
2022-01-08 17:30:56.557951 CRITICAL AppDaemon: Pinned apps were: ['Test']
2022-01-08 17:30:56.558536 CRITICAL AppDaemon: Thread will be restarted
2022-01-08 17:30:56.559056 INFO AppDaemon: Adding thread 0
2022-01-08 17:30:57.579504 CRITICAL AppDaemon: Thread thread-0 has died
2022-01-08 17:30:57.581215 CRITICAL AppDaemon: Pinned apps were: ['Test']
2022-01-08 17:30:57.582270 CRITICAL AppDaemon: Thread will be restarted
2022-01-08 17:30:57.583521 INFO AppDaemon: Adding thread 0
2022-01-08 17:30:58.599792 CRITICAL AppDaemon: Thread thread-0 has died
2022-01-08 17:30:58.601167 CRITICAL AppDaemon: Pinned apps were: ['Test']
2022-01-08 17:30:58.602128 CRITICAL AppDaemon: Thread will be restarted
2022-01-08 17:30:58.602719 INFO AppDaemon: Adding thread 0
2022-01-08 17:30:59.619435 CRITICAL AppDaemon: Thread thread-0 has died
2022-01-08 17:30:59.621382 CRITICAL AppDaemon: Pinned apps were: ['Test']
2022-01-08 17:30:59.622401 CRITICAL AppDaemon: Thread will be restarted
2022-01-08 17:30:59.623404 INFO AppDaemon: Adding thread 0
</pre>

**Comment by ReneTode** [comment]
this is wrong:
```
self.run_every(self.ForceClearZones(True), datetime.now(), 30)
```
run_every expects a callback, not a function.
so change it to:
```
    self.run_every(self.ForceClearZones, datetime.now(), 30, my_arg= True)
def ForceClearZones(self, kwargs):
    bytime = kwargs["my_arg"]
```

**Comment by meluvalli** [comment]
Perfect!  That worked :)  Thank you!  So one other quick question if you don't mind.  If I want to call ForceClearZones within another def ran by listen_state within the same file, how would I call it?  The way I had it before, I could just call it with 
<pre>
self.ForceClearZones(False)
</pre>

**Comment by Justihar** [comment]
You can still call the method outside of a run_every() as you have in your example. All you are doing when using self.ForceClearZones in run_every() is passing a method to the run_every() method that expects a specific signature (self, kwargs). Other than that, the method is usable anywhere else in your code without passing it into a scheduler callback.

**Comment by meluvalli** [comment]
Hmm.  When I call it that way from another part of the code, I get a Traceback error.

<pre>
    bytime = kwargs["my_arg"]
TypeError: 'bool' object is not subscriptable
</pre>


So My code is now like this as per the directions which fixed the run_every...
<pre>
      def ForceClearZones(self, kwargs):
            bytime = kwargs["my_arg"]
</pre>

However, if I call the ForceClearZones from within a listen_state  def, it throws that error above.

**Comment by meluvalli** [comment]
Solved it :)   

Needs to be:
<pre>
self.ForceClearZones({'my_arg': True})
</pre>

**Comment by meluvalli** [comment]
Thank you guys for your help!!!

**Comment by ReneTode** [comment]
there are 2 possibilities:
put the code in a function like you did before and call it from any callback:
```
    self.run_every(self.cb, datetime.now(), 30, my_arg= True)
   self.listen_state(self.cb2, entity, my_arg = False)
def cb(self, kwargs):
    bytime = kwargs["my_arg"]
    self.ForceClearZones(bytime)
def cb2(self, entity, attribute, old, new, kwargs):
     bytime = kwargs["my_arg"]
    self.ForceClearZones(bytime)
```
or from another callback call the schedular(run_every callback) with:
```
    self.run_every(self.ForceClearZones, datetime.now(), 30, my_arg= True)
   self.listen_state(self.cb2, entity, my_arg = False)
def ForceClearZones(self, kwargs):
    bytime = kwargs["my_arg"]
def cb2(self, entity, attribute, old, new, kwargs):
    self.ForceClearZones({"my_arg": True})
```
and if you got more questions then we will be pleased to help on our discord server.
