### ISSUE TITLE
 turn_on, turn_off and toggle methods in the entity class do not pass the in the service domain

### ISSUE THREAD

**Issue by eBoon123** [AppDaemon/appdaemon#1456]
Reporting after discussion with proggie on Discord.

Running Frenk's appdaemon addon 0.8.0 with AppDaemon 4.2.0 - turn_on, turn_off, and toggle throw an error.

Here is a test program to demonstrate:

```
class Testing(hass.Hass):
  def initialize(self):
     #self.turn_on("group.greatroomtablelamps")  # This does NOT work
     self.call_service("homeassistant/turn_on", entity_id= "group.greatroomtablelamps")  # This does work
```

Error:

`2022-01-11 13:59:12.225931 WARNING tom: ------------------------------------------------------------
2022-01-11 13:59:12.226256 WARNING tom: Unexpected error running initialize() for tom
2022-01-11 13:59:12.227508 WARNING tom: ------------------------------------------------------------
2022-01-11 13:59:12.228827 WARNING tom: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/tom.py", line 17, in initialize
    self.turn_on(entity_id="group.greatroomtablelamps")
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/site-packages/appdaemon/plugins/hass/hassapi.py", line 29, in coro_wrapper
    return await coro(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/plugins/hass/hassapi.py", line 379, in turn_on
    await self.get_entity_api(namespace, entity_id).turn_on(**kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/entity.py", line 488, in turn_on
    return await self.call_service("turn_on", **kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/entity.py", line 358, in call_service
    return await self.AD.services.call_service(namespace, domain, service, kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/services.py", line 158, in call_service
    raise ServiceException(
appdaemon.exceptions.ServiceException: ('Unknown service (%s/%s/%s) in call_service from %s', 'default', 'group', 'turn_on', 'tom')
`
Thank you

**Comment by Odianosen25** [comment]
@eBoon123,

This has now been fixed in dev, and will hopefully be released this weekend.

Closing this for now.
