### ISSUE TITLE
self.turn_on / self.turn_off on groups is no longer working

### ISSUE THREAD

**Issue by jeroenvdwaal** [AppDaemon/appdaemon#1460]
Hi all,

I have one app that is using `self.turn_on` and `self.turn_off` on a group. Recently, that doesn't seem to work anymore. I get the following exception in the code:

```console
2022-01-13 11:20:06.567885 WARNING garden: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/outdoor_lights.py", line 56, in initialize
    self.__control_lights(None)
  File "/config/appdaemon/apps/outdoor_lights.py", line 78, in __control_lights
    self.__power(False)
  File "/config/appdaemon/apps/outdoor_lights.py", line 94, in __power
    self.turn_off(switches)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/site-packages/appdaemon/plugins/hass/hassapi.py", line 29, in coro_wrapper
    return await coro(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/plugins/hass/hassapi.py", line 419, in turn_off
    await self.get_entity_api(namespace, entity_id).turn_off(**kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/entity.py", line 502, in turn_off
    return await self.call_service("turn_off", **kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/entity.py", line 358, in call_service
    return await self.AD.services.call_service(namespace, domain, service, kwargs)
  File "/usr/lib/python3.9/site-packages/appdaemon/services.py", line 158, in call_service
    raise ServiceException(
appdaemon.exceptions.ServiceException: ('Unknown service (%s/%s/%s) in call_service from %s', 'default', 'group', 'turn_off', 'garden')
```
I have fixed the problem for now by replacing the code with: 
- `self.service_call('homeassistant/turn_on', entity_id='group.gardenswitches')` 
- `self.service_call('homeassistant/turn_off', entity_id='group.gardenswitches')`

### The group itself

```yml
GardenSwitches:
  name: Garden Switches
  entities:
    - switch.frontdoor
    - switch.spotlights_front
    - switch.spotlights_back
    - light.hue_backdoor
```
### Version info

```console
Add-on version: 0.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.1  (amd64 / qemux86-64)
 Home Assistant Core: 2021.12.8
 Home Assistant Supervisor: 2021.12.2
```

I hope that this is enough information for you guys. Keep up the good work :-)

**Comment by jeroenvdwaal** [comment]
@Justihar thank you. I am happy that the issue is on the radar :-) Should I close this issue, or do you like to close it, after the next release?

**Comment by Justihar** [comment]
Probably just leave it open so others are aware, thanks.

**Comment by Odianosen25** [comment]
This has been fixed so will be closin it
