### ISSUE TITLE
AppDaemon 4.2.0 disconnecting from HA 

### ISSUE THREAD

**Issue by matejdro** [AppDaemon/appdaemon#1465]
After updating to AppDaemon 4.2.0, connection to the Home Assistant became very unstable for me.

Every time a service call is triggered, there is a chance that AppDaemon will disconnect with the following error:

```
2022-01-15 10:02:25.464709 ERROR HASS: ------------------------------------------------------------
2022-01-15 10:02:25.464935 INFO HASS: Previous message repeated 1 times
2022-01-15 10:02:25.465036 ERROR HASS: Unexpected error during call_plugin_service()
2022-01-15 10:02:25.465168 ERROR HASS: Service: default.cover.set_cover_position Arguments: {'entity_id': 'cover.raw_dnevna_levo', 'position': 100}
2022-01-15 10:02:25.465301 ERROR HASS: ------------------------------------------------------------
2022-01-15 10:02:25.465605 ERROR HASS: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/plugins/hass/hassplugin.py", line 519, in call_plugin_service
    r = await self.session.post(api_url, headers=headers, json=data, verify_ssl=self.cert_verify)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host my.homeassistant.domain.com:443 ssl:default [Connection reset by peer]
```

I can easily reproduce it by triggering a command a bunch of times:

```python
for i in range(0, 50):
    await self.call_service("cover/set_cover_position", entity_id="cover.raw_dnevna_levo", position=100)
```

Downgrading back to 4.1.0 resolves the issue, so it seems something regressed in 4.2.0.

This is with official docker image for both 4.1.0 and 4.2.0 and Home Assistant 2021.12.9. Connection to Home Assistant goes through nginx 1.17.9 reverse proxy.

**Comment by Justihar** [comment]
I just tested myself and not seeing the same behavior and I have been running dev for a while before the release. The call_service() method was changed to not return a result in order to make it more performant and if you want a result returned you need to add return_result=True FYI. Due to this you might see some different behavior depending on how some apps are written.

```python
class Test(adbase.ADBase):
    async def initialize(self):
        self.adapi = self.get_ad_api()

        for i in range(0, 50):
            await self.adapi.call_service("light/turn_off", entity_id="light.garage_rgb")
```

```
2022-01-15 10:25:59.961239 INFO AppDaemon: Reloading Module: /Users/justin/Projects/appdaemon_dev/conf/apps/test/test.py
2022-01-15 10:25:59.964763 INFO AppDaemon: Initializing app test using class Test from module test
2022-01-15 10:25:59.968645 INFO test: Previous message repeated 49 times
2022-01-15 10:25:59.968922 DEBUG test: call_service: light/turn_off, {'entity_id': 'light.garage_rgb'}
```

**Comment by matejdro** [comment]
It looks like return_result change was the culprit, since it sent all of those calls asynchronously, it overwhelmed my nginx proxy. I really should read changelogs more carefully.

Thanks a lot for your help.
