### ISSUE TITLE
DeprecationWarning in Asyncio causing initalize errors

### ISSUE THREAD

**Issue by khmikkelsen** [AppDaemon/appdaemon#1547]
I've been stuck on addon version 0.8.2 for a while now, because updating to anything above will lead to all my apps giving warnings like the following:

```
DeprecationWarning: There is no current event loop
asyncio.get_event_loop()
File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 216, in inner_sync_wrapper
self.scene_handler = self.listen_state(self.scene_selector_changed, self._scene_selector)
File "/config/appdaemon/apps/dimmer_switch.py", line 54, in initialize
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
response = future.result()
File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app
2022-07-14 14:03:45.633531 WARNING kitchen_dimmer: Traceback (most recent call last):
2022-07-14 14:03:45.631481 WARNING kitchen_dimmer: ------------------------------------------------------------
2022-07-14 14:03:45.630241 WARNING kitchen_dimmer: Unexpected error running initialize() for kitchen_dimmer
2022-07-14 14:03:45.628772 WARNING kitchen_dimmer: ------------------------------------------------------------
```

And as a result of this warning, the initialization will fail. The error occurs with every listen_state call in `initialize()` and afaik the anatomy of an AppDaemon app hasn't changed, so I'm a bit perplexed as to what I can do here?

**Comment by Justihar** [comment]
You're going to need to at least share your code under initialize() to get an idea as to what is going on. The exception is indicating an issue with line 54 in dimmer_switch.py.

**Comment by khmikkelsen** [comment]
```
def initialize(self):
        self.log("initializing ...")
        try:
            self.log(f'args: {self.args}')
            self._dimmer = self.args['dimmer_switch']
            self._light_group = self.args['light_group']
            self._scene_selector = self.args['scene_selector']
        except (TypeError, ValueError) as e:
            self.log('Incomplete configuration', level="ERROR")
            raise e
        self.scene_handler = self.listen_state(self.scene_selector_changed, self._scene_selector)

def scene_selector_changed(self, entity, attribute, old, new, kwargs):
        state = self.get_state(self._scene_selector)
        self.log(f'Scene selected: {state}')
        self.turn_on(f'scene.{state}', transition=0.4)
```
That's kinda my point, this is happening to all my apps, same error message on the first call to `self.listen_state()`, in each of them when they initialize.

**Comment by khmikkelsen** [comment]
Do you have a link for the specific repo, I'll continue there then. Thanks in advance.

**Comment by Justihar** [comment]
https://github.com/hassio-addons/addon-appdaemon
