### ISSUE TITLE
AppDeamon issue on HA supervised (see also #75437 HA Core)

### ISSUE THREAD

**Issue by Kouwe-sudo** [AppDaemon/appdaemon#1551]
The problem

I didn't see anyone reporting this issue but with the latest release of HA 2022.7 there are issues with (at least) AppDeamon but only in combination with HA Supervised. I use the same configuration with HA OS on a raspberry Pi and everything works fine there. I run HA Supervised on a NUC with an I5-processor. I also noticed that the log is filled rapidly which even gives issues with free available space. Perhaps this line in the log is helpful: **homeassistant.components.http.view] Unable to serialize to JSON**

AppDeamon does start but then it keeps retrying because of:
WARNING HASS: Error getting Home Assistant state for None
WARNING HASS: Code: 500, error: 500: Internal Server Error
WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds

I don't think the add-on itself is causing the problem because it works fine on the raspberry. I think something is missing after the last update of python.
What version of Home Assistant Core has the issue?

2022.07 (1-5)
What was the last working version of Home Assistant Core?

2022-6.7
What type of installation are you running?

Home Assistant Supervised
Integration causing the issue

AppDeamon

Log:
`-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.9.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.7.5
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

2022-07-19 14:37:30.373633 INFO HASS: Evaluating startup conditions
2022-07-19 14:37:30.380542 INFO HASS: Startup condition met: hass state=RUNNING
2022-07-19 14:37:30.380866 INFO HASS: All startup conditions met
2022-07-19 14:37:30.414710 WARNING HASS: Error getting Home Assistant state for None
2022-07-19 14:37:30.415174 WARNING HASS: Code: 500, error: 500: Internal Server Error
2022-07-19 14:37:30.415601 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds`

**Comment by Justihar** [comment]
If you're having free disk space errors, I'd look at that first... either a disk space issue or possibly permissions. With that kind of issue, nothing is going to work right.

**Comment by Kouwe-sudo** [comment]
Thanks for your good advise but I think 40 Gb of space for a log is plenty enough I assume. Besides that the problem of a rapidly filling of the logfiles was over with as soon as stopped Appdeamon. And I don't have these problems on a raspberry with the same configuration so I can't imagine it has anything to do with permissions. Running 2022.06.7 (and older) doesn't cause any trouble too.

**Comment by Justihar** [comment]
The problem is not with AD or the logs, the problem is that AD is not staying connected to HA indicated by this log....

`2022-07-19 14:37:30.415601 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds`

If you are seeing a high number of those errors then there is something wrong with AD configuration, HA configuration, docker, networking, OS config, etc..... one of those is causing an issue.

**Comment by Kouwe-sudo** [comment]
And just that is the reason I reported it. Except loading the new HA-release I didn't do anything. My raspberry works and my NUC with HA supervised doesn't. When I go back to the old 2022.06-release everything works just fine. I think it's not a bad guess it has anything to do with the new release. I suppose AppDeamon is the same I assume for both the raspberry and the NUC.

**Comment by Justihar** [comment]
Ah ok, you may want to check on issues with Supervised as I heard someone mention there have been issues with it. If you find out, please let me know. Take care.

**Comment by FernandoWahl** [comment]
I have the same problem after the update

**Comment by Kouwe-sudo** [comment]
And just that is the reason I reported it. Except loading the new HA-release I didn't do anything. My raspberry works and my NUC with HA supervised doesn't. When I go back to the old 2022.06-release everything works just fine. I think it's not a bad guess it has anything to do with the new release. I suppose AppDeamon is the same I assume for both the raspberry and the NUC.

**Comment by Kouwe-sudo** [comment]
And the sad thing is that nobody seems to care.

**Comment by acockburn** [comment]
This looks like a problem with the HASS add-on not AppDaemon, there hasn't been a new release of AD for several months, so the code probably hasn't changed at all since you had a working version. Please open an issue with the add-on - we do not support that here, as none of us actually use it. The version number you gave is not an AppDaemon version.

Also, please avoid the passive aggressive comments if you actually want us to help, we do this in our spare time for free.

**Comment by Kouwe-sudo** [comment]
My comment wasn't at all ment to be aggressive but I hope you agree that it is annoying to see that since the HA release of 2022-07 a part of the automations don't work anymore and an old iPad is hanging on the wall with a black screen. If you had read all off my comments you might have seen that I even agree with your conclusion that the problem doesn't have anything to do with Appdeamon itself because it still works flawlessly on a Raspberry Pi with Ha 2022-08-3. 
But everyone is pointing to someone else and advise to report it somewhere else already resulting in two issues with the same problem. I even doubt it has anything to do with the add-on. I assume there's a discrepancy between HA OS and HA supervised and that's why I reported the issue there first with the result that they pointed at the Appdaemon-guys. 
Having said all this I'm still really happy with all the efforts volunteers put in this whole community. But don't forget that users also spent a lot of time making use of all this.

**Comment by Justihar** [comment]
This Github page is primarily for support of the AD core project although we try to help as much as we can but as Andrew pointed out, most of us in the support group are not running AD as an add-on or running Supervised. I can confirm that I am running HA 2022.7.5 and AD is not having any issues connecting to it so I feel confident as well that this is not directly an AD issue. Additionally, Frenck manages the AD add-on and he is good about reaching out to us when the add-on container is going to implement newer versions of dependencies that are not compatible with AD. So I'm really not sure what is going on here. We know for certain that there is an issue with AD connecting to HA so maybe start off by sharing your appdaemon.yaml configuration file.

**Comment by acockburn** [comment]
Figuring out what the connection issue is would be a first step - to get more info you need to start AD with the debug flag set. For CORE you can do that on the command line, not sure if that is possible supervised. Setting debug will give the actual exception for the connection and would be a step forward.

**Comment by Kouwe-sudo** [comment]
**This is my yaml for Appdaemon.** Take note that I use BS4 but I use exactly the same configuration on my Raspberry without a problem. And skipped BS4 doesn't change anything.

init_commands: []
python_packages:
  - bs4
system_packages: []
log_level: debug

**Is this helpful when debug flag is set?**
'
2022-08-15 19:14:30.412638 WARNING HASS: Error getting Home Assistant state for None
2022-08-15 19:14:30.413021 WARNING HASS: Code: 500, error: 500: Internal Server Error
2022-08-15 19:14:30.413344 DEBUG AppDaemon: Clearing callbacks for HASS
2022-08-15 19:14:30.413533 DEBUG AppDaemon: Event type:plugin_stopped:
2022-08-15 19:14:30.413711 DEBUG AppDaemon: {'name': 'HASS'}
2022-08-15 19:14:30.413892 DEBUG AppDaemon: process_event_callbacks() default {'event_type': 'plugin_stopped', 'data': {'name': 'HASS'}}
2022-08-15 19:14:30.414150 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-08-15 19:14:30.414498 DEBUG HASS: ------------------------------------------------------------
2022-08-15 19:14:30.414659 DEBUG HASS: Unexpected error:
2022-08-15 19:14:30.414820 DEBUG HASS: ------------------------------------------------------------
2022-08-15 19:14:30.415593 DEBUG HASS: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 359, in get_updates
    await self.evaluate_started(True, self.hass_booting)
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 246, in evaluate_started
    state = await self.get_complete_state()
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 148, in get_complete_state
    for state in hass_state:
TypeError: 'NoneType' object is not iterable
2022-08-15 19:14:30.415737 DEBUG HASS: ------------------------------------------------------------
2022-08-15 19:14:30.416029 DEBUG AppDaemon: thread_async loop, args={'function': <bound method Events.process_event of <appdaemon.events.Events object at 0x7f1171f54bb0>>, 'args': ('admin', {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Error getting Home Assistant state for None', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.412743', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412570), 'formatted_message': '2022-08-15 19:14:30.412743 WARNING HASS: Error getting Home Assistant state for None'}}), 'kwargs': {}}
2022-08-15 19:14:30.416339 DEBUG AppDaemon: thread_async loop, args={'function': <bound method Events.process_event of <appdaemon.events.Events object at 0x7f1171f54bb0>>, 'args': ('admin', {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Code: 500, error: 500: Internal Server Error', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.413159', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412925), 'formatted_message': '2022-08-15 19:14:30.413159 WARNING HASS: Code: 500, error: 500: Internal Server Error'}}), 'kwargs': {}}
2022-08-15 19:14:30.416606 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.process_event of <appdaemon.stream.adstream.ADStream object at 0x7f117134b910>>, 'args': ({'event_type': 'plugin_stopped', 'data': {'name': 'HASS'}, 'namespace': 'default'},), 'kwargs': {}}
2022-08-15 19:14:30.416923 DEBUG AppDaemon: thread_async loop, args={'function': <bound method Events.process_event of <appdaemon.events.Events object at 0x7f1171f54bb0>>, 'args': ('admin', {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Disconnected from Home Assistant, retrying in 5 seconds', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.414263', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 414054), 'formatted_message': '2022-08-15 19:14:30.414263 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds'}}), 'kwargs': {}}
2022-08-15 19:14:30.417348 DEBUG AppDaemon: Event type:__AD_LOG_EVENT:
2022-08-15 19:14:30.417566 DEBUG AppDaemon: {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Error getting Home Assistant state for None', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.412743', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412570), 'formatted_message': '2022-08-15 19:14:30.412743 WARNING HASS: Error getting Home Assistant state for None'}
2022-08-15 19:14:30.417794 DEBUG AppDaemon: process_event_callbacks() admin {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Error getting Home Assistant state for None', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.412743', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412570), 'formatted_message': '2022-08-15 19:14:30.412743 WARNING HASS: Error getting Home Assistant state for None'}}
2022-08-15 19:14:30.418126 DEBUG AppDaemon: Event type:__AD_LOG_EVENT:
2022-08-15 19:14:30.418336 DEBUG AppDaemon: {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Code: 500, error: 500: Internal Server Error', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.413159', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412925), 'formatted_message': '2022-08-15 19:14:30.413159 WARNING HASS: Code: 500, error: 500: Internal Server Error'}
2022-08-15 19:14:30.418604 DEBUG AppDaemon: process_event_callbacks() admin {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Code: 500, error: 500: Internal Server Error', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.413159', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 412925), 'formatted_message': '2022-08-15 19:14:30.413159 WARNING HASS: Code: 500, error: 500: Internal Server Error'}}
2022-08-15 19:14:30.418908 DEBUG AppDaemon: Event type:__AD_LOG_EVENT:
2022-08-15 19:14:30.419092 DEBUG AppDaemon: {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Disconnected from Home Assistant, retrying in 5 seconds', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.414263', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 414054), 'formatted_message': '2022-08-15 19:14:30.414263 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds'}
2022-08-15 19:14:30.419373 DEBUG AppDaemon: process_event_callbacks() admin {'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Disconnected from Home Assistant, retrying in 5 seconds', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.414263', 'ts': datetime.datetime(2022, 8, 15, 19, 14, 30, 414054), 'formatted_message': '2022-08-15 19:14:30.414263 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds'}}
2022-08-15 19:14:30.419728 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.process_event of <appdaemon.stream.adstream.ADStream object at 0x7f117134b910>>, 'args': ({'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Error getting Home Assistant state for None', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.412743', 'formatted_message': '2022-08-15 19:14:30.412743 WARNING HASS: Error getting Home Assistant state for None'}, 'namespace': 'admin'},), 'kwargs': {}}
2022-08-15 19:14:30.419969 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.process_event of <appdaemon.stream.adstream.ADStream object at 0x7f117134b910>>, 'args': ({'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Code: 500, error: 500: Internal Server Error', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.413159', 'formatted_message': '2022-08-15 19:14:30.413159 WARNING HASS: Code: 500, error: 500: Internal Server Error'}, 'namespace': 'admin'},), 'kwargs': {}}
2022-08-15 19:14:30.420250 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.process_event of <appdaemon.stream.adstream.ADStream object at 0x7f117134b910>>, 'args': ({'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'HASS', 'message': 'Disconnected from Home Assistant, retrying in 5 seconds', 'type': 'log', 'log_type': 'main_log', 'asctime': '2022-08-15 19:14:30.414263', 'formatted_message': '2022-08-15 19:14:30.414263 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds'}, 'namespace': 'admin'},), 'kwargs': {}}

**Comment by Justihar** [comment]
This is just the add-on configuration, not the appdaemon.yaml config which exists in the AD docker container. As far as I can tell, all of the exceptions thrown in the debug log are due to the fact that your AD container is unable to connect to HA.

**Comment by Justihar** [comment]
Also, FYI, @FernandoWahl opened a ticket with the add-on repo. https://github.com/hassio-addons/addon-appdaemon/issues/207

**Comment by Kouwe-sudo** [comment]
Okay, so here is my AppDaemon yaml. I believe nothing special.
 
`---
secrets: /config/secrets.yaml
appdaemon:
  latitude: xx.xxxx
  longitude: -xx.xxx
  elevation: 2
  time_zone: Europe/Vienna
  plugins:
    HASS:
      type: hass
      
hadashboard:
 
dash_url: http://182.100.0.15:5050
  
http:
  url: http://127.0.0.1:5050
admin:
api:

dashboard_dir: /config/appdaemon/dashboards
`

**Comment by Justihar** [comment]
Just a heads up, I wouldn't recommend exposing the HA dashboard directly to the internet.

So this is a very basic appdaemon.yaml config and as expected, the HA plugin settings need to be passed in as environment variables. In this case, the dockerStart.sh file is going to rely on `$HA_URL`, `$TOKEN` being passed into the docker environment for it to know how to connect to HA. Optionally `$DASH_URL`, `$TIMEZONE`, `$LATITUDE`, `$LONGITUDE`, and `$ELEVATION`. You can look at this file as a reference, as this is what is ran when AD is started in a docker container: https://github.com/AppDaemon/appdaemon/blob/master/dockerStart.sh

You may want to dig around and see if you can tell if the HA_URL and TOKEN environment variables are being passed into the docker container. Without them, AD will have no way to know how to connect to HA.

**Comment by Ari-Sig** [comment]
I'm running hass.io in proxmox  on intel nuc, if I go into python3 to check for modules with help("modules") there is no Appdaemon, i added the /config/custom_components/hacs/repositories to the $PYTHONPATH it finds appdaemon but fails when importing with a error on line 8 "from ..enums import HacsCategory, HacsDispatchEvent", I added the /config/custom_components/hacs where i found the enums.py it also fails with another error "ImportError: attempted relative import with no known parent package". Haven't used the d-link powerstrip for a while so i'm not shure when it broke, Every thing is updated to the latest version.
I have supervised version of hass and ad is installed as a add-on. I got the 5 seconds line in appdaemon.log but after changing in appdaemon.yaml --> ha_url: to my nabu casa address it is gone, last line in my main_log is info appdaemon initializing app .......
my last line in the appdaemon plugin log is info: starting appdaemon...

**Comment by Kouwe-sudo** [comment]
Where do you find your nabu casa address? And even worse: If you don't have one. Cause the need of nasa basa would mean that you can only use Appdeamon with a paid subscription. That can't be true can it?

**Comment by acockburn** [comment]
AppDaemon has no reliance on Nabu Casa - the devs have never received a cent in payment, and there is no plan to do so, AppDamon core is completely free.

It may be that for some reason the HASS add-on for AppDaemon has a dependency, I don't know as none of us use it that way, but AppDaemon core will connect to any local AD URL as long as the authentication is setup correctly.

**Comment by Ari-Sig** [comment]
I have Nabu Casa subscription and used that address in appdaemon.yaml, the 5 seconds retry stopped coming but I can’t get appdaemon to work.

**Comment by Ari-Sig** [comment]
Has someone been able to find a workaround for this problem ?

In the cont-init folder the 00... and 01... files exist but appdaemon.sh dose not but still the same exit code ?
---
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/appdaemon.sh
cont-init: info: /etc/cont-init.d/appdaemon.sh exited 0
---

**Comment by Ari-Sig** [comment]
sorry for spamming but I really need this and have one more thing.

If I add appdaemon to python packages on the configuration page, I get in the log file.:
Requirement already satisfied: appdaemon in /usr/lib/python3.10/site-packages (4.2.1)
Requirement already satisfied: cchardet==2.1.7 in /usr/lib/python3.10/site-packages (from appdaemon) (2.1.7)
Requirement already satisfied: sockjs==0.11.0 in /usr/lib/python3.10/site-packages (from appdaemon) (0.11.0)
and a lot more lines like that but still there is no appdaemon in the site-packages folder so how can the requirement be satisfied ?

**Comment by Justihar** [comment]
> sorry for spamming but I really need this and have one more thing.
> 
> 
> 
> If I add appdaemon to python packages on the configuration page, I get in the log file.:
> 
> Requirement already satisfied: appdaemon in /usr/lib/python3.10/site-packages (4.2.1)
> 
> Requirement already satisfied: cchardet==2.1.7 in /usr/lib/python3.10/site-packages (from appdaemon) (2.1.7)
> 
> Requirement already satisfied: sockjs==0.11.0 in /usr/lib/python3.10/site-packages (from appdaemon) (0.11.0)
> 
> and a lot more lines like that but still there is no appdaemon in the site-packages folder so how can the requirement be satisfied ?

It's OK. I'm mobile at the moment but if you're using the add-on, you shouldn't be specifying appdaemon as a package to install. If you're 100% sure that appdaemon isn't installed in the docker container that is created by the add-on, then there is something wrong with the add-on and we don't support that package here, it has its own GitHub repo.

**Comment by Ari-Sig** [comment]
When installing the appdaemon add-on in ha supervised the log file in the add-on page looks like every thing is ok and running but when going on a terminal window and entering python3 then help("modules") there is no appdaemon there and running the script that I was able to run before from the command line fails because of the missing appdaemon module ( and like I said I'm not sure when this failed, appdaemon update, ha update or something else ). Trying to install appdaemon package and other test was only a desperate try to get this working. Using appdaemon was the only way I found working, to integrate my d-link Wi-Fi Smart Power Strip DSP-W245 and I hate to have it broken.

**Comment by Justihar** [comment]
Supplied you with answer on Discord. If you believe there is an issue with the AD add-on package, please contact the maintainer otherwise spin up your own instance of AD within a docker container or a python virtual environment.

**Comment by Kouwe-sudo** [comment]
Thanks for your suggestion but did you try it out? I did (on a machine with docker Ubuntu) and it gives exactly the same error when connecting with HA. Mind me, I don't blame you, but I can't believe we are the only ones with this problem but the developers (of the addon) don't seem to care. Or did someone found a workaround?

**Comment by Justihar** [comment]
> Thanks for your suggestion but did you try it out? I did (on a machine with docker Ubuntu) and it gives exactly the same error when connecting with HA. Mind me, I don't blame you, but I can't believe we are the only ones with this problem but the developers (of the addon) don't seem to care. Or did someone found a workaround?

After some troubleshooting with @Ari-Sig, I found that their issue was trying to run an AD app, that is designed to run within the AD framework from the command line.

Your issue is that AD will not connect to HA which is an entirely different issue. Only a few people have reported your particular issue so it could be an edge case but probably pretty easy to fix with some troubleshooting.

**Comment by Ari-Sig** [comment]
That is not entirely true. The AD app that I'm not able to run now was working fine with a switch in home assistant that changed a input boolean that appdaemon listened to and turned on or off a d-link smart power strip socked. Running it from the command line was part of my troubleshooting because when I was tweaking the code I found online for my power strip running it like that worked 100% fine on my hassio supervisor install.

**Comment by Kouwe-sudo** [comment]
> Your issue is that AD will not connect to HA which is an entirely different issue. Only a few people have reported your particular issue so it could be an edge case but probably pretty easy to fix with some  
@Justihar.

If it's probably easy to fix. Is there anyone out there you can solve this problem? I would be grateful.

**Comment by Justihar** [comment]
> > Your issue is that AD will not connect to HA which is an entirely different issue. Only a few people have reported your particular issue so it could be an edge case but probably pretty easy to fix with some
> > @Justihar.
> 
> If it's probably easy to fix. Is there anyone out there you can solve this problem? I would be grateful.

I don't think anyone is going to solve it for you and I don't run _Supervised_ however I did provide you with some valuable information as far as how the connection information for AD to connect to HA is passed into the AD docker environment. Did you happen to take a look at that?

I would first make sure that the correct and "connectable" data is being passed into the environment. The most important is going to be **ha_url**, **token** and optionally **cert_verify**. If the information being passed into the docker environment that tells AD how to connect to HA is not a valid address then AD is not going to have the correct information to make that connection.

**Comment by Kouwe-sudo** [comment]
@Justihar 

I do run Supervised. The official version with no comments on the System page. For that reason it would be strange that I have to take care of a token and that sort of thing. I run supervised to not have to worry about that. I only tried your suggestion to run it inside docker to see if that would help (including a longlife token)

**Comment by Justihar** [comment]
> @Justihar
> 
> I do run Supervised. The official version with no comments on the System page. For that reason it would be strange that I have to take care of a token and that sort of thing. I run supervised to not have to worry about that. I only tried your suggestion to run it inside docker to see if that would help (including a longlife token)

I'm not suggesting that you manually add the token. I am suggesting that you dig around to verify that the correct data is being passed into the docker container. I'm really sorry that I don't have more detailed information for you but I don't run supervised. I can only tell you the information that AD is expecting to make a successful connection. The creation of the AD docker container and information being passed to the AD docker container is all out of the scope of the AD project and I have no personal experience with it.

**Comment by nickrout** [comment]
Appdaemon works on supervised here via the addon. No issues.
