### ISSUE TITLE
entity.state not usable in async functions

### ISSUE THREAD

**Issue by chatziko** [AppDaemon/appdaemon#1605]
Using `entity.state` inside an async function fails. This can be reproduced with a trivial app:

```python
import hassapi as hass

class MyApp(hass.Hass):
    async def initialize(self):
        entity = self.get_entity("zone.home")
        s = entity.state
```
This fails with a cryptic message (I guess it has to do with the internal use of `get_state` which is `async`):
```
2022-11-20 14:29:51.061465 WARNING myapp: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/myapp.py", line 6, in initialize
    s = entity.state
  File "/usr/lib/python3.10/site-packages/appdaemon/entity.py", line 532, in state
    return self.states.state
  File "/usr/lib/python3.10/site-packages/appdaemon/entity.py", line 19, in __get__
    stateattrs = utils.EntityStateAttrs(instance.get_state(attribute="all", copy=False, default={}))
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 185, in __init__
    self.__dict__ = AttrDict.from_nested_dict(dict)
TypeError: __dict__ must be set to a dictionary, not a '_asyncio.Task'
```

Since the state can be fetched synchronously, and `entity.state` is much more readable than `await entity.get_state()`, it would be nice to support it. (If supporting it is not possible, it should at least be documented that `entity.state` is not available in async functions).

**Comment by Odianosen25** [comment]
Hello @chatziko,

you right unfortunately it’s not supported yet. We won’t say it’s impossible, but you right it should be documented.

we will try to document it.

kind regards

**Comment by chatziko** [comment]
As a hackish workaround: manually setting `entity.states` allows to later call `entity.state`.
```python
import hassapi as hass
import appdaemon.utils as utils

class MyApp(hass.Hass):
    async def initialize(self):
        entity = self.get_entity("zone.home")

        # this allows to later call entity.state from an async function
        entity.states = utils.EntityStateAttrs(await entity.get_state(attribute="all", copy=False, default={}))

        self.log("state %s", entity.state)
```
So I can create my own wrapper of `get_entity` and do this automatically for all entities. Not ideal, but good for now.

**Comment by acockburn** [comment]
Fixed in 4.2.2
