### ISSUE TITLE
Home Assistant with SSL, using traefik with letsencryt, ValueError: scheme “https” is invalid

### ISSUE THREAD

**Issue by KoenDierckx** [AppDaemon/appdaemon#1613]
Running all my docker applications with traefik reverse proxy, using letsencrypt ssl
My internal HomeAssistant url is therefore https enabled

Making a similar setup for appdaemon with this docker compose:

`
version: '3.8'
services:
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: always
    environment:
      - TZ=Europe/Brussels
      - HA_URL=https://home.example.com
      - TOKEN=XXXXXXXX
      - DASH_URL=https://appdaemon.example.com
    volumes:
      - ./config:/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.appdaemon.rule=Host(`appdaemon.example.com`)
      - traefik.http.routers.appdaemon.entrypoints=web, websecure
      - traefik.http.routers.appdaemon.tls.certresolver=cloudflare
      - traefik.http.routers.appdaemon.service=appdaemon
      - traefik.http.services.appdaemon.loadbalancer.server.port=5050
    networks:
      - traefik
networks:
  traefik:
    external: true
`

`
2022-12-11 20:43:19.392235 DEBUG AppDaemon: Clearing callbacks for HASS
2022-12-11 20:43:19.392448 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-11 20:43:19.392787 DEBUG HASS: ------------------------------------------------------------
2022-12-11 20:43:19.393193 DEBUG HASS: Unexpected error:
2022-12-11 20:43:19.393640 DEBUG HASS: ------------------------------------------------------------
2022-12-11 20:43:19.394475 DEBUG HASS: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/appdaemon/plugins/hass/hassplugin.py", line 304, in get_updates
    self.ws = websocket.create_connection("{}/api/websocket".format(url), sslopt=sslopt)
  File "/usr/local/lib/python3.9/site-packages/websocket/_core.py", line 606, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.9/site-packages/websocket/_core.py", line 249, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/usr/local/lib/python3.9/site-packages/websocket/_http.py", line 117, in connect
    hostname, port, resource, is_secure = parse_url(url)
  File "/usr/local/lib/python3.9/site-packages/websocket/_url.py", line 66, in parse_url
    raise ValueError("scheme %s is invalid" % scheme)
ValueError: scheme “https” is invalid
`

**Comment by acockburn** [comment]
This is strange as AD should be passing "wss" as the scheme, what is your "ha_url" set to in appdaemon.yaml for the mass plugin?
