### ISSUE TITLE
Namespace disappeared and is not being recreated

### ISSUE THREAD

**Issue by lukaszwawrzyk** [AppDaemon/appdaemon#1617]
In last few days my app stopped working, I get this error in log:

```
  File "/config/appdaemon/apps/core/persistent_state.py", line 16, in initialize
    self._base.add_entity(self._entity_id, state="on", attributes=initial_state, namespace="persistent")
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 642, in add_entity
    await self.get_entity_api(namespace, entity_id).add(state, attributes)
  File "/usr/lib/python3.10/site-packages/appdaemon/entity.py", line 303, in add
    await self.AD.state.add_entity(namespace, entity_id, state, attributes)
  File "/usr/lib/python3.10/site-packages/appdaemon/state.py", line 471, in add_entity
    self.state[namespace][entity] = state
KeyError: 'persistent'
```

I am trying to create an entity if it does not exist in namespace "persistent".

appdemon.yaml looks like this:

```
secrets: /config/secrets.yaml
appdaemon:
  <private information>
  plugins:
    HASS:
      type: hass
  namespaces:
    persistent:
      writeback: safe
```

It used to work before. Now for some reason namespace "persistent" does not exist.

I tried to create namespace from code and I have this error:

```
2022-12-16 22:02:09.157976 WARNING AppDaemon: ------------------------------------------------------------
2022-12-16 22:02:09.158521 WARNING AppDaemon: Unexpected error in namespace setup
2022-12-16 22:02:09.160010 WARNING AppDaemon: ------------------------------------------------------------
2022-12-16 22:02:09.161677 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/state.py", line 104, in add_persistent_namespace
    self.state[namespace] = utils.PersistentDict(nspath_file, safe)
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 90, in __init__
    super().__init__(filename, writeback=True)
  File "/usr/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.10/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available
```

is the docker image broken?

**Comment by squady** [comment]
Same error here since the last update

**Comment by acockburn** [comment]
When you say the latest update, what are you referring to? Appdaemon hasn’t had an update for quite a few months.

**Comment by squady** [comment]
Hi,
My HA installation suggested  me an appdaemon update a few days ago. I did it today and now I have this error too.

**Comment by Justihar** [comment]
I have looked into this a little bit and although I don't understand what changed to create this error, I can make one suggestion. Try creating a backup of the namespaces directory and remove it from the AD configuration folder or just rename it so AD can create a new one. If that fixes it, there might have been some changes in the newest version of Python 3.10 that broke compatibility with database created in a previous version. Yes, this will remove any persistent states you have created yourself but I don't have a better suggestion at this time.

**Comment by squady** [comment]
Hi @Justihar .
Thank you for taking the time to check it out.
I no longer facing the error after deleting the namespace folder.
Thank you for your help !

**Comment by lukaszwawrzyk** [comment]
Yes, it also worked for me, though data is lost. It would be worth to figure out how to prevent this in the future.

**Comment by randomletters** [comment]
Thank you.  That helped.

The solution unfortunately involves deleting the stored data, but it allows the code to function.

Steps to fix:

Update appdaemon
Goto terminal
Goto appdaemon/namespaces
Remove mynamespace.db
Restart appdaemon
