### ISSUE TITLE
Repeating loop of save_hybrid_namespaces for old app

### ISSUE THREAD

**Issue by jaycrossler** [AppDaemon/appdaemon#1624]
I had an old app called 'watcher', and when I moved the app files to a new Home Assistant machine and copied it over, I'm now getting this bizarre behavior - even after re-deleting the app directory.  Every second, this message is sent to the AppDaemon log file.  It doesn't seem to otherwise do any damage...:

```
2023-01-14 09:50:12.172705 WARNING AppDaemon: Traceback (most recent call last): File "/usr/lib/python3.10/site-packages/appdaemon/utility_loop.py", line 173, in loop self.AD.state.save_hybrid_namespaces() File "/usr/lib/python3.10/site-packages/appdaemon/state.py", line 680, in save_hybrid_namespaces self.state[ns].sync() KeyError: 'watcher'
--
2023-01-14 09:50:12.171423 WARNING AppDaemon: ------------------------------------------------------------
2023-01-14 09:50:12.170002 WARNING AppDaemon: Unexpected error during utility()
```

**Comment by acockburn** [comment]
You probably need to delete and recreate the namespace DB under <appdaemon_dir>/namespaces.

We have also seen some issues that appear to be related to a format change in the DB files. Again, delete and recreate is the easiest solution.
