### ISSUE TITLE
TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'

### ISSUE THREAD

**Issue by bbrendon** [AppDaemon/appdaemon#1637]
I just updated my appdaemon and it pulls dev.  I have a new error appearing which looks like it might be related to the last commit.

https://github.com/AppDaemon/appdaemon/commit/9ac5750d7c760bf916d84cb0c7966f89d90ab27d

```
appdaemon  | 2023-01-29 20:25:41.390813 WARNING AppDaemon: Invalid callback handle 'None' in cancel_timer() from app FrontDoorLight
appdaemon  | 2023-01-29 20:25:41.393817 WARNING FrontDoorLight: ------------------------------------------------------------
appdaemon  | 2023-01-29 20:25:41.394406 WARNING FrontDoorLight: Unexpected error in worker for App FrontDoorLight:
appdaemon  | 2023-01-29 20:25:41.397519 WARNING FrontDoorLight: Worker Ags: {'id': '83deb8058ece48618fe7d59b50c901d5', 'name': 'FrontDoorLight', 'objectid': '10625fc85a5e45f8acb9577269979285',
 'type': 'state', 'function': <bound method MotionLights.motion of <motion_lights.MotionLights object at 0x7f7dc54dab80>>, 'attribute': 'state', 'entity': 'binary_sensor.front_door', 'new_stat
e': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 36, 'kwargs': {'__thread_id': 'thread-36'}}
appdaemon  | 2023-01-29 20:25:41.398438 WARNING FrontDoorLight: ------------------------------------------------------------
appdaemon  | 2023-01-29 20:25:41.404603 WARNING FrontDoorLight: Traceback (most recent call last):
appdaemon  |   File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 986, in worker
appdaemon  |     funcref(
appdaemon  |   File "/conf/apps/motion_lights.py", line 76, in motion
appdaemon  |     self.handle = self.run_in(self.light_off, delay)
appdaemon  |   File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 226, in inner_sync_wrapper
appdaemon  |     f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
appdaemon  |   File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 346, in run_coroutine_threadsafe
appdaemon  |     result = future.result(self.AD.internal_function_timeout)
appdaemon  |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
appdaemon  |     return self.__get_result()
appdaemon  |   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
appdaemon  |     raise self._exception
appdaemon  |   File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 2391, in run_in
appdaemon  |     i, d = divmod(delay, 1)
appdaemon  | TypeError: unsupported operand type(s) for divmod(): 'str' and 'int'
appdaemon  |
appdaemon  | 2023-01-29 20:25:41.405253 WARNING FrontDoorLight: ------------------------------------------------------------

```

**Comment by bbrendon** [comment]
what if this line (https://github.com/AppDaemon/appdaemon/blob/9ac5750d7c760bf916d84cb0c7966f89d90ab27d/appdaemon/adapi.py#L2391) was changed to
```
i, d = divmod(float(delay), 1)
```

**Comment by bbrendon** [comment]
Never mind. I guess it's listed as a breaking change. So 🤷🏻

**Comment by acockburn** [comment]
Yeah - I slipped it in as a breaking change but I can do something like you suggest and make it a non breaking change ..

**Comment by acockburn** [comment]
OK, I made it accept strings again the way you suggested. Let me know if it works for you.
