### ISSUE TITLE
pop from empty deque error

### ISSUE THREAD

**Issue by thomasdelaet** [AppDaemon/appdaemon#1650]
Hey hey,

I'm getting regular errors like the below in my logs. Any idea what might cause them? Version I'm running is 4.2.1

```
2023-02-23 13:08:59.303646 WARNING AppDaemon: ------------------------------------------------------------
2023-02-23 13:08:59.304253 WARNING AppDaemon: Unexpected error during process_event()
2023-02-23 13:08:59.304976 WARNING AppDaemon: ------------------------------------------------------------
2023-02-23 13:08:59.306114 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/appdaemon/lib/python3.9/site-packages/appdaemon/events.py", line 247, in process_event
    await self.AD.http.stream_update(namespace, mydata)
  File "/srv/appdaemon/lib/python3.9/site-packages/appdaemon/http.py", line 726, in stream_update
    self.AD.thread_async.call_async_no_wait(self.stream.process_event, data)
  File "/srv/appdaemon/lib/python3.9/site-packages/appdaemon/thread_async.py", line 52, in call_async_no_wait
    self.appq.put_nowait({"function": function, "args": args, "kwargs": kwargs})
  File "/usr/lib/python3.9/asyncio/queues.py", line 155, in put_nowait
    self._wakeup_next(self._getters)
  File "/usr/lib/python3.9/asyncio/queues.py", line 68, in _wakeup_next
    waiter = waiters.popleft()
IndexError: pop from an empty deque

2023-02-23 13:08:59.306453 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
This looks like its related to the admin interface - do the errors disapear of you disable ity?

**Comment by thomasdelaet** [comment]
Thanks for the tip! I'll try that.

**Comment by thomasdelaet** [comment]
I've commented out the admin: part of the config but am still getting those errors regularly. Any further suggestions on where to look?

tnx!!!

**Comment by thomasdelaet** [comment]
Any suggestions?
