### ISSUE TITLE
MQTT Sensors are not working anymore

### ISSUE THREAD

**Issue by tshoblak** [AppDaemon/appdaemon#1755]
### What happened?

After the most recent update on HA, these errors start to show and therefore all my sensors (Doors and Windows) are unavailable.

### Version

0.12.0

### Installation type

Home Assistant add-on

### Relevant log output

```sh
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-04-14 10:39:45.235658 INFO MQTT: Unable to decode MQTT message
2023-04-14 10:39:45.236115 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 302, in mqtt_on_message
    payload = payload.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-04-14 10:40:38.605811 INFO MQTT: Unable to decode MQTT message
2023-04-14 10:40:38.610329 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 302, in mqtt_on_message
    payload = payload.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-04-14 10:40:53.019830 INFO MQTT: Unable to decode MQTT message
2023-04-14 10:40:53.020268 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 302, in mqtt_on_message
    payload = payload.decode()
```

**Comment by Odianosen25** [comment]
Hello @tshoblak, not sure this relates to us. Can you confirm what the app was doing?

**Comment by tshoblak** [comment]
The app I am using is app. 
https://github.com/XaF/qolsysgw#installing-appdaemon
Some sensors are working but others are not.

**Comment by tshoblak** [comment]
Closing this one. It has nothing to do with you guys.
Thank you
