### ISSUE TITLE
Getting 'Object of type datetime is not JSON serializable' error on 4.4.2

### ISSUE THREAD

**Issue by carlos-sarmiento** [AppDaemon/appdaemon#1757]
### What happened?

A long time ago I created an automation to update an `input_datetime` entity. Since at least 7 days ago it has been throwing an error on AppDaemon

### Version

4.4.2

### Installation type

Docker container

### Relevant log output

```sh
2023-04-19 01:38:02.600203 ERROR HASS: ------------------------------------------------------------
2023-04-19 01:38:02.604380 INFO HASS: Previous message repeated 1 times
2023-04-19 01:38:02.604998 ERROR HASS: Unexpected error during call_plugin_service()
2023-04-19 01:38:02.605528 ERROR HASS: Service: default.input_datetime.set_datetime Arguments: {'entity_id': 'input_datetime.some_datetime', 'datetime': datetime.datetime(2023, 4, 19, 12, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>)}
2023-04-19 01:38:02.605941 ERROR HASS: ------------------------------------------------------------
2023-04-19 01:38:02.606500 ERROR HASS: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 543, in call_plugin_service
    self.update_perf(bytes_sent=len(json.dumps(data)), bytes_recv=len(await r.text()), requests_sent=1)
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

### Relevant code in the app or config file that caused the issue

```sh
self.call_service("input_datetime/set_datetime",
                          entity_id=entity,
                          datetime=start)
```

**Comment by acockburn** [comment]
Looks like this was caused by code to measure plug-in traffic introduced a couple of releases ago - I’ll put a fix in the next release.
