### ISSUE TITLE
Schedy App/script not working after update Appdaemon add-on to 0.15.2

### ISSUE THREAD

**Issue by MarekLe** [AppDaemon/appdaemon#1896]
### What happened?

After update Appdaemon Add-on to 0.15.2 Schedy App not working. There is error in Appdaemon's log.

### Version

4.4.2

### Installation type

Home Assistant add-on

### Relevant log output

```sh
2023-12-11 18:27:50.394131 INFO AppDaemon: Loading app schedy using class SchedyApp from module hass_apps_loader
2023-12-11 18:27:50.402666 WARNING schedy: ------------------------------------------------------------
2023-12-11 18:27:50.403066 WARNING schedy: Unexpected error initializing app: schedy:
2023-12-11 18:27:50.403321 WARNING schedy: ------------------------------------------------------------
2023-12-11 18:27:50.404988 WARNING schedy: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1035, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 338, in init_object
    "object": app_class(
              ^^^^^^^^^^
  File "/config/apps/hass_apps/loader.py", line 29, in _proxy_loader
    app_mod = _import_app_module(app_package)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/hass_apps/loader.py", line 24, in _import_app_module
    return importlib.import_module(mod_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/apps/hass_apps/schedy/app.py", line 14, in <module>
    from .. import common
  File "/config/apps/hass_apps/common.py", line 9, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

2023-12-11 18:27:50.405619 WARNING schedy: ------------------------------------------------------------
```

**Comment by acockburn** [comment]
is this still an issue?
