### ISSUE TITLE
Some apps not reloaded after HA restart

### ISSUE THREAD

**Issue by matejdro** [AppDaemon/appdaemon#2011]
### What happened?

After restarting HA, some of my apps will not properly restart. They will stay in `terminated` mode until I also restart AppDaemon:

![image](https://github.com/AppDaemon/appdaemon/assets/507922/912949f4-0615-45ae-9332-de64386b7797)

In above case, `BlindController` app and all of its dependencies do not restart, but it seems random (sometimes, other apps will not restart)

Logs below are from me restarting HA (resulting in above screenshot).

### Version

4.4.2

### Installation type

Docker container

### Relevant log output

```sh
2024-05-22 08:41:44.290053 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-05-22 08:41:49.388480 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-05-22 08:41:54.485958 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-05-22 08:41:57.251020 WARNING HASS: Error getting services - retrying
Task exception was never retrieved
future: <Task finished name='Task-572' coro=<HassPlugin.run_hass_service_check() done, defined at /usr/local/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py:763> exception=ClientResponseError(RequestInfo(url=URL('https://my_home_assistant/api/services'), method='GET', headers=<CIMultiDictProxy('Host': 'myhomeassistant', 'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlOTM5NTY5Mzk2MTA0ZGEzYWE2NDRkZjVlMjExMWM2MCIsImlhdCI6MTY3MzQzNzY5NSwiZXhwIjoxOTg4Nzk3Njk1fQ.MVBKx7BjgCGPJG-BFLTsORSJjf9j1INTsEVCYTkbwog', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.10 aiohttp/3.8.4')>, real_url=URL('https://ha.matejdro.com/api/services')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Server': 'nginx/1.17.9', 'Date': 'Wed, 22 May 2024 06:41:57 GMT', 'Content-Type': 'text/html', 'Content-Length': '157', 'Connection': 'keep-alive')>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 772, in run_hass_service_check
    hass_services = await self.get_hass_services()
  File "/usr/local/lib/python3.10/site-packages/appdaemon/plugins/hass/hassplugin.py", line 732, in get_hass_services
    r.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://my_home_assistant/api/services')
2024-05-22 08:41:59.616276 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-05-22 08:42:04.720228 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-05-22 08:42:09.867609 INFO HASS: Connected to Home Assistant 2024.5.4
2024-05-22 08:42:10.014710 INFO HASS: Evaluating startup conditions
2024-05-22 08:42:19.600830 INFO HASS: Startup condition met: hass state=RUNNING
2024-05-22 08:42:19.601119 INFO HASS: All startup conditions met
2024-05-22 08:42:19.662954 INFO AppDaemon: Processing restart for HASS
2024-05-22 08:42:19.672231 INFO AppDaemon: Terminating controller
2024-05-22 08:42:19.673124 INFO AppDaemon: Terminating blinds_sleep_mode
2024-05-22 08:42:19.673753 INFO AppDaemon: Terminating blinds_balcony_rain_shield
2024-05-22 08:42:19.674375 INFO AppDaemon: Terminating blinds_heat_shield
2024-05-22 08:42:19.675006 INFO AppDaemon: Terminating blinds_movie_mode
2024-05-22 08:42:19.675591 INFO AppDaemon: Terminating blinds_window_semi_open
2024-05-22 08:42:19.676197 INFO AppDaemon: Terminating blinds_glare_control
2024-05-22 08:42:19.676747 INFO AppDaemon: Terminating blinds_sun_position
2024-05-22 08:42:19.677392 INFO AppDaemon: Terminating blinds_manual_control
2024-05-22 08:42:19.678170 INFO AppDaemon: Terminating morning_alert
2024-05-22 08:42:19.678708 INFO AppDaemon: Terminating home_out
2024-05-22 08:42:19.679602 INFO AppDaemon: Terminating light_stack
2024-05-22 08:42:19.680154 INFO AppDaemon: Terminating account_checker
2024-05-22 08:42:19.680327 INFO AppDaemon: Calling terminate() for account_checker
2024-05-22 08:42:19.680850 INFO AppDaemon: Terminating motion_lights_mala_soba
2024-05-22 08:42:19.681457 INFO AppDaemon: Terminating motion_lights_kuhinja
2024-05-22 08:42:19.682110 INFO AppDaemon: Terminating motion_lights_jedilnica
2024-05-22 08:42:19.682705 INFO AppDaemon: Terminating motion_lights_dnevna
2024-05-22 08:42:19.683439 INFO AppDaemon: Terminating motion_lights_hodnik
2024-05-22 08:42:19.684103 INFO AppDaemon: Terminating motion_lights_spalnica
2024-05-22 08:42:19.684760 INFO AppDaemon: Terminating motion_lights_kopalnica
2024-05-22 08:42:19.685446 INFO AppDaemon: Terminating spalnica_media_sync
2024-05-22 08:42:19.685935 INFO AppDaemon: Terminating simrail_alert
2024-05-22 08:42:19.686418 INFO AppDaemon: Terminating jedilnica
2024-05-22 08:42:19.686870 INFO AppDaemon: Terminating mala_soba
2024-05-22 08:42:19.687395 INFO AppDaemon: Terminating balkon_a
2024-05-22 08:42:19.687870 INFO AppDaemon: Terminating balkon_b
2024-05-22 08:42:19.688352 INFO AppDaemon: Terminating balkon_c
2024-05-22 08:42:19.688832 INFO AppDaemon: Terminating dnevna_levo
2024-05-22 08:42:19.689301 INFO AppDaemon: Terminating dnevna_desno
2024-05-22 08:42:19.694998 INFO AppDaemon: Reloading Module: /conf/apps/light_stack.py
2024-05-22 08:42:19.707519 INFO AppDaemon: Reloading Module: /conf/apps/account_checker.py
2024-05-22 08:42:19.708292 INFO AppDaemon: Reloading Module: /conf/apps/motion_lights.py
2024-05-22 08:42:19.709620 INFO AppDaemon: Reloading Module: /conf/apps/spalnica_media_sync.py
2024-05-22 08:42:19.710487 INFO AppDaemon: Reloading Module: /conf/apps/extra/simrail_alert.py
2024-05-22 08:42:19.711231 INFO AppDaemon: Reloading Module: /conf/apps/blinds/raw_tasmota_blinds_control.py
2024-05-22 08:42:19.711964 INFO AppDaemon: Reloading Module: /conf/apps/home_out.py
2024-05-22 08:42:19.714370 INFO AppDaemon: Reloading Module: /conf/apps/morning_alert.py
2024-05-22 08:42:19.715895 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/manual_control.py
2024-05-22 08:42:19.716653 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/sun_position.py
2024-05-22 08:42:19.717546 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/glare_control.py
2024-05-22 08:42:19.718259 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/window_semi_open.py
2024-05-22 08:42:19.718930 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/movie_mode.py
2024-05-22 08:42:19.719647 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/heat_shield.py
2024-05-22 08:42:19.720371 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/balcony_rain_shield.py
2024-05-22 08:42:19.721160 INFO AppDaemon: Reloading Module: /conf/apps/blinds/modules/sleep_mode.py
2024-05-22 08:42:19.721860 INFO AppDaemon: Reloading Module: /conf/apps/blinds/blind_controller.py
2024-05-22 08:42:19.723531 INFO AppDaemon: Loading app light_stack using class LightStack from module light_stack
2024-05-22 08:42:19.724839 INFO AppDaemon: Loading app account_checker using class AccountChecker from module account_checker
2024-05-22 08:42:19.728051 INFO AppDaemon: Loading app motion_lights_mala_soba using class MotionLights from module motion_lights
2024-05-22 08:42:19.729577 INFO AppDaemon: Loading app motion_lights_kuhinja using class MotionLights from module motion_lights
2024-05-22 08:42:19.731023 INFO AppDaemon: Loading app motion_lights_jedilnica using class MotionLights from module motion_lights
2024-05-22 08:42:19.732408 INFO AppDaemon: Loading app motion_lights_dnevna using class MotionLights from module motion_lights
2024-05-22 08:42:19.733814 INFO AppDaemon: Loading app motion_lights_hodnik using class MotionLights from module motion_lights
2024-05-22 08:42:19.735145 INFO AppDaemon: Loading app motion_lights_spalnica using class MotionLights from module motion_lights
2024-05-22 08:42:19.736526 INFO AppDaemon: Loading app motion_lights_kopalnica using class MotionLights from module motion_lights
2024-05-22 08:42:19.737849 INFO AppDaemon: Loading app spalnica_media_sync using class SpalnicaMediaSync from module spalnica_media_sync
2024-05-22 08:42:19.739081 INFO AppDaemon: Loading app simrail_alert using class SimrailAlert from module simrail_alert
2024-05-22 08:42:19.740373 INFO AppDaemon: Loading app jedilnica using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.741706 INFO AppDaemon: Loading app mala_soba using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.742991 INFO AppDaemon: Loading app balkon_a using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.744313 INFO AppDaemon: Loading app balkon_b using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.745627 INFO AppDaemon: Loading app balkon_c using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.746905 INFO AppDaemon: Loading app dnevna_levo using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.748190 INFO AppDaemon: Loading app dnevna_desno using class RawTasmotaBlindsMover from module raw_tasmota_blinds_control
2024-05-22 08:42:19.749526 INFO AppDaemon: Loading app home_out using class HomeOutScript from module home_out
2024-05-22 08:42:19.750820 INFO AppDaemon: Loading app morning_alert using class MorningAlert from module morning_alert
2024-05-22 08:42:19.752139 INFO AppDaemon: Loading app blinds_manual_control using class ManualControlModule from module manual_control
2024-05-22 08:42:19.753509 INFO AppDaemon: Loading app blinds_sun_position using class SunPositionModule from module sun_position
2024-05-22 08:42:19.754840 INFO AppDaemon: Loading app blinds_glare_control using class GlareControlModule from module glare_control
2024-05-22 08:42:19.756209 INFO AppDaemon: Loading app blinds_window_semi_open using class WindowSemiOpenModule from module window_semi_open
2024-05-22 08:42:19.757923 INFO AppDaemon: Loading app blinds_movie_mode using class MovieModeModule from module movie_mode
2024-05-22 08:42:19.759282 INFO AppDaemon: Loading app blinds_heat_shield using class HeatShieldModule from module heat_shield
2024-05-22 08:42:19.760882 INFO AppDaemon: Loading app blinds_balcony_rain_shield using class BalconyRainShieldModule from module balcony_rain_shield
2024-05-22 08:42:19.762016 INFO AppDaemon: Loading app blinds_sleep_mode using class SleepModeModule from module sleep_mode
2024-05-22 08:42:19.762986 INFO AppDaemon: Loading app controller using class BlindController from module blind_controller
2024-05-22 08:42:19.766146 INFO AppDaemon: Calling initialize() for light_stack
2024-05-22 08:42:19.769681 INFO AppDaemon: Calling initialize() for account_checker
2024-05-22 08:42:19.820927 INFO AppDaemon: Calling initialize() for motion_lights_mala_soba
2024-05-22 08:42:19.826577 INFO motion_lights_mala_soba: Initial state: ReadyState
2024-05-22 08:42:19.827060 INFO AppDaemon: Calling initialize() for motion_lights_kuhinja
2024-05-22 08:42:19.833602 INFO motion_lights_kuhinja: Initial state: ReadyState
2024-05-22 08:42:19.834133 INFO AppDaemon: Calling initialize() for motion_lights_jedilnica
2024-05-22 08:42:19.839251 INFO motion_lights_jedilnica: Initial state: ReadyState
2024-05-22 08:42:19.839693 INFO AppDaemon: Calling initialize() for motion_lights_dnevna
2024-05-22 08:42:19.846553 INFO motion_lights_dnevna: Initial state: ReadyState
2024-05-22 08:42:19.847150 INFO AppDaemon: Calling initialize() for motion_lights_hodnik
2024-05-22 08:42:19.852455 INFO motion_lights_hodnik: Initial state: ReadyState
2024-05-22 08:42:19.852989 INFO AppDaemon: Calling initialize() for motion_lights_spalnica
2024-05-22 08:42:19.859793 INFO motion_lights_spalnica: Initial state: ReadyState
2024-05-22 08:42:19.860554 INFO AppDaemon: Calling initialize() for motion_lights_kopalnica
2024-05-22 08:42:19.866484 INFO motion_lights_kopalnica: Previous message repeated 1 times
2024-05-22 08:42:19.866703 INFO motion_lights_kopalnica: Initial state: ReadyState
2024-05-22 08:42:19.867314 INFO AppDaemon: Calling initialize() for spalnica_media_sync
2024-05-22 08:42:19.869225 INFO AppDaemon: Calling initialize() for simrail_alert
2024-05-22 08:42:19.870938 INFO AppDaemon: Calling initialize() for jedilnica
2024-05-22 08:42:19.872218 INFO AppDaemon: Calling initialize() for mala_soba
2024-05-22 08:42:19.873507 INFO AppDaemon: Calling initialize() for balkon_a
2024-05-22 08:42:19.874713 INFO AppDaemon: Calling initialize() for balkon_b
2024-05-22 08:42:19.875951 INFO AppDaemon: Calling initialize() for balkon_c
2024-05-22 08:42:19.877204 INFO AppDaemon: Calling initialize() for dnevna_levo
2024-05-22 08:42:19.878511 INFO AppDaemon: Calling initialize() for dnevna_desno
2024-05-22 08:42:19.879738 INFO AppDaemon: Calling initialize() for home_out
2024-05-22 08:42:20.262584 WARNING home_out: home_out: Entity appdaemon.home_out not found in namespace default
2024-05-22 08:42:20.263206 INFO AppDaemon: home_out: Entity appdaemon.home_out created in namespace: default
2024-05-22 08:42:20.271207 INFO AppDaemon: Calling initialize() for morning_alert
2024-05-22 08:43:10.152038 INFO HASS: Registering new service variable/update_sensor
2024-05-22 08:43:10.153876 INFO HASS: Registering new service tts/google_translate_say
2024-05-22 08:43:10.154021 INFO HASS: Registering new service tts/cloud_say
2024-05-22 08:43:10.155085 INFO HASS: Registering new service notify/join
2024-05-22 08:43:10.155246 INFO HASS: Registering new service notify/mobile_app_pixel_7_pro
2024-05-22 08:43:10.155430 INFO HASS: Registering new service notify/mobile_app_galaxy_watch4_classic_2a2m
2024-05-22 08:43:10.155601 INFO HASS: Registering new service notify/notify
2024-05-22 08:43:10.155775 INFO HASS: Registering new service notify/tv
2024-05-22 08:43:10.155920 INFO HASS: Registering new service notify/telegram
2024-05-22 08:43:10.157747 INFO HASS: Registering new service backup/create
2024-05-22 08:43:10.157913 INFO HASS: Registering new service mqtt/publish
2024-05-22 08:43:10.158066 INFO HASS: Registering new service mqtt/dump
2024-05-22 08:43:10.158194 INFO HASS: Registering new service mqtt/reload
2024-05-22 08:43:10.158357 INFO HASS: Registering new service python_script/test
2024-05-22 08:43:10.158500 INFO HASS: Registering new service python_script/rgb_set
2024-05-22 08:43:10.158640 INFO HASS: Registering new service python_script/light_hold_down_room
2024-05-22 08:43:10.158787 INFO HASS: Registering new service python_script/media_mode_power_toggle
2024-05-22 08:43:10.158958 INFO HASS: Registering new service python_script/toggle_with_transition
2024-05-22 08:43:10.159129 INFO HASS: Registering new service python_script/hello_world
2024-05-22 08:43:10.159317 INFO HASS: Registering new service python_script/sync_spalnica_radio
2024-05-22 08:43:10.159501 INFO HASS: Registering new service python_script/reload
2024-05-22 08:43:10.159734 INFO HASS: Registering new service login_control/clear_refresh_tokens
2024-05-22 08:43:10.159921 INFO HASS: Registering new service schedule/reload
2024-05-22 08:43:10.160132 INFO HASS: Registering new service zwave_js/set_config_parameter
2024-05-22 08:43:10.160297 INFO HASS: Registering new service zwave_js/bulk_set_partial_config_parameters
2024-05-22 08:43:10.160464 INFO HASS: Registering new service zwave_js/refresh_value
2024-05-22 08:43:10.160652 INFO HASS: Registering new service zwave_js/set_value
2024-05-22 08:43:10.160825 INFO HASS: Registering new service zwave_js/multicast_set_value
2024-05-22 08:43:10.160992 INFO HASS: Registering new service zwave_js/ping
2024-05-22 08:43:10.161165 INFO HASS: Registering new service zwave_js/invoke_cc_api
2024-05-22 08:43:10.161302 INFO HASS: Registering new service zwave_js/refresh_notifications
2024-05-22 08:43:10.161446 INFO HASS: Registering new service zwave_js/reset_meter
2024-05-22 08:43:10.161602 INFO HASS: Registering new service counter/increment
2024-05-22 08:43:10.161755 INFO HASS: Registering new service counter/decrement
2024-05-22 08:43:10.161913 INFO HASS: Registering new service counter/reset
2024-05-22 08:43:10.162082 INFO HASS: Registering new service counter/set_value
2024-05-22 08:43:10.162264 INFO HASS: Registering new service calendar/create_event
2024-05-22 08:43:10.162430 INFO HASS: Registering new service calendar/list_events
2024-05-22 08:43:10.162605 INFO HASS: Registering new service calendar/get_events
2024-05-22 08:43:10.162785 INFO HASS: Registering new service webostv/button
2024-05-22 08:43:10.162954 INFO HASS: Registering new service webostv/command
2024-05-22 08:43:10.163118 INFO HASS: Registering new service webostv/select_sound_output
2024-05-22 08:43:10.163302 INFO HASS: Registering new service device_tracker/see
2024-05-22 08:43:10.163487 INFO HASS: Registering new service switch/turn_off
2024-05-22 08:43:10.163654 INFO HASS: Registering new service switch/turn_on
2024-05-22 08:43:10.163817 INFO HASS: Registering new service switch/toggle
2024-05-22 08:43:10.164017 INFO HASS: Registering new service denonavr/get_command
2024-05-22 08:43:10.164169 INFO HASS: Registering new service denonavr/set_dynamic_eq
2024-05-22 08:43:10.164315 INFO HASS: Registering new service denonavr/update_audyssey
2024-05-22 08:43:10.164480 INFO HASS: Registering new service button/press
2024-05-22 08:43:10.164651 INFO HASS: Registering new service number/set_value
2024-05-22 08:43:10.164802 INFO HASS: Registering new service select/select_first
2024-05-22 08:43:10.164960 INFO HASS: Registering new service select/select_last
2024-05-22 08:43:10.165109 INFO HASS: Registering new service select/select_next
2024-05-22 08:43:10.165254 INFO HASS: Registering new service select/select_option
2024-05-22 08:43:10.165400 INFO HASS: Registering new service select/select_previous
2024-05-22 08:43:10.165565 INFO HASS: Registering new service time/set_value
2024-05-22 08:43:10.165730 INFO HASS: Registering new service vacuum/start
2024-05-22 08:43:10.165875 INFO HASS: Registering new service vacuum/pause
2024-05-22 08:43:10.166019 INFO HASS: Registering new service vacuum/return_to_base
2024-05-22 08:43:10.166166 INFO HASS: Registering new service vacuum/clean_spot
2024-05-22 08:43:10.166310 INFO HASS: Registering new service vacuum/locate
2024-05-22 08:43:10.166454 INFO HASS: Registering new service vacuum/stop
2024-05-22 08:43:10.166598 INFO HASS: Registering new service vacuum/set_fan_speed
2024-05-22 08:43:10.166742 INFO HASS: Registering new service vacuum/send_command
2024-05-22 08:43:10.166907 INFO HASS: Registering new service roborock/get_maps
2024-05-22 08:43:10.167070 INFO HASS: Registering new service remote/turn_off
2024-05-22 08:43:10.167223 INFO HASS: Registering new service remote/turn_on
2024-05-22 08:43:10.167373 INFO HASS: Registering new service remote/toggle
2024-05-22 08:43:10.167518 INFO HASS: Registering new service remote/send_command
2024-05-22 08:43:10.167662 INFO HASS: Registering new service remote/learn_command
2024-05-22 08:43:10.167807 INFO HASS: Registering new service remote/delete_command
2024-05-22 08:43:10.167974 INFO HASS: Registering new service weather/get_forecast
2024-05-22 08:43:10.168175 INFO HASS: Registering new service weather/get_forecasts
2024-05-22 08:43:10.168447 INFO HASS: Registering new service template/reload
2024-05-22 08:43:10.168685 INFO HASS: Registering new service fan/turn_on
2024-05-22 08:43:10.168935 INFO HASS: Registering new service fan/turn_off
2024-05-22 08:43:10.169174 INFO HASS: Registering new service fan/toggle
2024-05-22 08:43:10.169396 INFO HASS: Registering new service fan/increase_speed
2024-05-22 08:43:10.169612 INFO HASS: Registering new service fan/decrease_speed
2024-05-22 08:43:10.169869 INFO HASS: Registering new service fan/oscillate
2024-05-22 08:43:10.170075 INFO HASS: Registering new service fan/set_direction
2024-05-22 08:43:10.170313 INFO HASS: Registering new service fan/set_percentage
2024-05-22 08:43:10.170517 INFO HASS: Registering new service fan/set_preset_mode
2024-05-22 08:43:10.170666 INFO HASS: Registering new service climate/turn_on
2024-05-22 08:43:10.170820 INFO HASS: Registering new service climate/turn_off
2024-05-22 08:43:10.170967 INFO HASS: Registering new service climate/toggle
2024-05-22 08:43:10.171096 INFO HASS: Registering new service climate/set_hvac_mode
2024-05-22 08:43:10.171222 INFO HASS: Registering new service climate/set_preset_mode
2024-05-22 08:43:10.171362 INFO HASS: Registering new service climate/set_aux_heat
2024-05-22 08:43:10.171490 INFO HASS: Registering new service climate/set_temperature
2024-05-22 08:43:10.171623 INFO HASS: Registering new service climate/set_humidity
2024-05-22 08:43:10.171759 INFO HASS: Registering new service climate/set_fan_mode
2024-05-22 08:43:10.171938 INFO HASS: Registering new service climate/set_swing_mode
2024-05-22 08:43:10.172130 INFO HASS: Registering new service automation/trigger
2024-05-22 08:43:10.172260 INFO HASS: Registering new service automation/toggle
2024-05-22 08:43:10.172385 INFO HASS: Registering new service automation/turn_on
2024-05-22 08:43:10.172520 INFO HASS: Registering new service automation/turn_off
2024-05-22 08:43:10.172661 INFO HASS: Registering new service automation/reload
2024-05-22 08:43:10.172821 INFO HASS: Registering new service update/install
2024-05-22 08:43:10.172948 INFO HASS: Registering new service update/skip
2024-05-22 08:43:10.173118 INFO HASS: Registering new service update/clear_skipped
2024-05-22 08:43:10.173279 INFO HASS: Registering new service telegram_bot/send_message
2024-05-22 08:43:10.173411 INFO HASS: Registering new service telegram_bot/send_photo
2024-05-22 08:43:10.173552 INFO HASS: Registering new service telegram_bot/send_sticker
2024-05-22 08:43:10.173692 INFO HASS: Registering new service telegram_bot/send_animation
2024-05-22 08:43:10.173832 INFO HASS: Registering new service telegram_bot/send_video
2024-05-22 08:43:10.173971 INFO HASS: Registering new service telegram_bot/send_voice
2024-05-22 08:43:10.174114 INFO HASS: Registering new service telegram_bot/send_document
2024-05-22 08:43:10.174256 INFO HASS: Registering new service telegram_bot/send_location
2024-05-22 08:43:10.174397 INFO HASS: Registering new service telegram_bot/send_poll
2024-05-22 08:43:10.174537 INFO HASS: Registering new service telegram_bot/edit_message
2024-05-22 08:43:10.174676 INFO HASS: Registering new service telegram_bot/edit_caption
2024-05-22 08:43:10.174816 INFO HASS: Registering new service telegram_bot/edit_replymarkup
2024-05-22 08:43:10.174955 INFO HASS: Registering new service telegram_bot/answer_callback_query
2024-05-22 08:43:10.175094 INFO HASS: Registering new service telegram_bot/delete_message
2024-05-22 08:43:10.175233 INFO HASS: Registering new service telegram_bot/leave_chat
2024-05-22 08:43:10.175396 INFO HASS: Registering new service telegram/reload
2024-05-22 08:43:10.175560 INFO HASS: Registering new service google/add_event
2024-05-22 08:43:10.175695 INFO HASS: Registering new service google/create_event
2024-05-22 08:43:10.175855 INFO HASS: Registering new service todoist/new_task
2024-05-22 08:43:10.176023 INFO HASS: Registering new service androidtv/adb_command
2024-05-22 08:43:10.176162 INFO HASS: Registering new service androidtv/learn_sendevent
2024-05-22 08:43:10.176296 INFO HASS: Registering new service androidtv/download
2024-05-22 08:43:10.176438 INFO HASS: Registering new service androidtv/upload
2024-05-22 08:43:10.176601 INFO HASS: Registering new service text/set_value
2024-05-22 08:43:10.176766 INFO HASS: Registering new service lock/unlock
2024-05-22 08:43:10.176902 INFO HASS: Registering new service lock/lock
2024-05-22 08:43:10.177042 INFO HASS: Registering new service lock/open
2024-05-22 08:43:18.874887 INFO AppDaemon: New client Admin Client connected
2024-05-22 08:44:59.809498 INFO AppDaemon: Client disconnection from Admin Client
2024-05-22 08:45:00.125908 INFO AppDaemon: New client Admin Client connected
```

### Relevant code in the app or config file that caused the issue

Blind controller is just regular Hass app:

```
class BlindController(hass.Hass):
    async def initialize(self):
      ...
```

```
global_modules:
  - blind_commons

controller:
  module: blind_controller
  class: BlindController
  global_dependencies:
    - blind_commons
  dependencies:
    - blinds_manual_control
    - blinds_sun_position
    - blinds_glare_control
    - blinds_window_semi_open
    - blinds_movie_mode
    - blinds_heat_shield
    - blinds_balcony_rain_shield
    - blinds_sleep_mode
```

### Anything else?

Note that `Calling initialized()` log line is missing for `blind_controller` app.

This started to happen couple of weeks ago. Possibly caused by a HA update?

**Comment by jsl12** [comment]
Both the Hass plugin and the app reloading logic have been entirely rewritten in the current dev branch, so I don't think this is an issue any more.
