### ISSUE TITLE
Start Loop AppDaemon Unexpected error during run()

### ISSUE THREAD

**Issue by wckd90** [AppDaemon/appdaemon#2179]
### What happened?

Hey guys, 

My AppDaemon won't start, I haven't changed my settings so I don't understand why this is happening. 

Can anyone find out what could be wrong? 

Thanks for any ideas! 
`

### Version

4.2.3

### Installation type

Home Assistant add-on

### Relevant log output

```sh
[14:05:14] INFO: Service AppDaemon exited with code 0 (by signal 0)
[14:05:15] INFO: Starting AppDaemon...
2024-12-15 14:05:17.694541 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-12-15 14:05:17.694700 INFO AppDaemon: Python version is 3.11.10
2024-12-15 14:05:17.694799 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-12-15 14:05:17.695612 INFO AppDaemon: Added log: AppDaemon
2024-12-15 14:05:17.695898 INFO AppDaemon: Added log: Error
2024-12-15 14:05:17.696019 INFO AppDaemon: Added log: Access
2024-12-15 14:05:17.696454 INFO AppDaemon: Added log: Diag
2024-12-15 14:05:17.851215 INFO AppDaemon: Initializing HTTP
2024-12-15 14:05:17.852139 INFO AppDaemon: Using 'ws' for event stream
2024-12-15 14:05:17.855728 INFO AppDaemon: Starting API
2024-12-15 14:05:17.858718 INFO AppDaemon: Starting Admin Interface
2024-12-15 14:05:17.859384 INFO AppDaemon: Starting Dashboards
2024-12-15 14:05:17.864837 WARNING AppDaemon: ------------------------------------------------------------
2024-12-15 14:05:17.865152 WARNING AppDaemon: Unexpected error during run()
2024-12-15 14:05:17.865835 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 160, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/admin_loop.py", line 18, in loop
    await self.AD.threading.get_callback_update()
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 82, in get_callback_update
    await self.set_state("_threading", "admin", "sensor.callbacks_average_fired", state=fired_avg)
  File "/usr/lib/python3.11/site-packages/appdaemon/state.py", line 632, in set_state
    plugin = await self.AD.plugins.get_plugin_object(namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/plugin_management.py", line 220, in get_plugin_object
    for name in self.plugins:
TypeError: 'NoneType' object is not iterable
2024-12-15 14:05:17.870019 INFO AppDaemon: Previous message repeated 1 times
2024-12-15 14:05:17.870177 INFO AppDaemon: AppDaemon Exited

(loop)

[14:05:18] INFO: Service AppDaemon exited with code 0 (by signal 0)
[14:05:19] INFO: Starting AppDaemon...
2024-12-15 14:05:22.189435 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-12-15 14:05:22.189659 INFO AppDaemon: Python version is 3.11.10
2024-12-15 14:05:22.189782 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-12-15 14:05:22.189892 INFO AppDaemon: Added log: AppDaemon
2024-12-15 14:05:22.190001 INFO AppDaemon: Added log: Error
2024-12-15 14:05:22.190096 INFO AppDaemon: Added log: Access
2024-12-15 14:05:22.190184 INFO AppDaemon: Added log: Diag
2024-12-15 14:05:22.364806 INFO AppDaemon: Initializing HTTP
2024-12-15 14:05:22.365289 INFO AppDaemon: Using 'ws' for event stream
2024-12-15 14:05:22.368112 INFO AppDaemon: Starting API
2024-12-15 14:05:22.370926 INFO AppDaemon: Starting Admin Interface
2024-12-15 14:05:22.371464 INFO AppDaemon: Starting Dashboards
2024-12-15 14:05:22.377408 WARNING AppDaemon: ------------------------------------------------------------
2024-12-15 14:05:22.377635 WARNING AppDaemon: Unexpected error during run()
2024-12-15 14:05:22.377766 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 160, in run
    loop.run_until_complete(asyncio.gather(*pending))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/admin_loop.py", line 18, in loop
    await self.AD.threading.get_callback_update()
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 82, in get_callback_update
    await self.set_state("_threading", "admin", "sensor.callbacks_average_fired", state=fired_avg)
  File "/usr/lib/python3.11/site-packages/appdaemon/state.py", line 632, in set_state
    plugin = await self.AD.plugins.get_plugin_object(namespace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/plugin_management.py", line 220, in get_plugin_object
    for name in self.plugins:
TypeError: 'NoneType' object is not iterable
2024-12-15 14:05:22.382004 INFO AppDaemon: Previous message repeated 1 times
2024-12-15 14:05:22.382157 INFO AppDaemon: AppDaemon Exited
[14:05:22] INFO: Service AppDaemon exited with code 0 (by signal 0)
[14:05:23] INFO: Starting AppDaemon...`
```

### Relevant code in the app or config file that caused the issue

```sh
idk
```

**Comment by acockburn** [comment]
This may be related to this HASS add-on issue:


<https://github.com/hassio-addons/addon-appdaemon/issues/287>
[287.png]
AppDaemon stops after updating to 0.15.0 · Issue #287 · hassio-addons/addon-appdaemon<https://github.com/hassio-addons/addon-appdaemon/issues/287>
github.com<https://github.com/hassio-addons/addon-appdaemon/issues/287>
