### ISSUE TITLE
docker image 3.0.5 installs AD 4

### ISSUE THREAD

**Issue by wsw70** [AppDaemon/appdaemon#844]
I updated my docker image by mistake to `:latest` and AD 4 was loaded. Everything was broken but never mind - I would just force the `3.0.5` tag for now pending configuration updates.

I pulled the `3.0.5` version which started fine but ended poorly:

```
Pulling appdaemon (acockburn/appdaemon:3.0.5)...
3.0.5: Pulling from acockburn/appdaemon
e79bb959ec00: Pull complete
d4b7902036fe: Pull complete
1b2a72d4e030: Pull complete
d54db43011fd: Pull complete
69d473365bb3: Pull complete
35b4aebab92b: Pull complete
60ddbccc0359: Pull complete
0b3c337d0c3e: Pull complete
dd92a33181e2: Pull complete
5996284cfd28: Pull complete
abcdd52b1ab7: Pull complete
c9724f14bedb: Pull complete
7e9730631551: Pull complete
Digest: sha256:b55a05ad4580558b2f7ef41e9b74ed889a87b50afca74c60d18d03a069a661f5
Status: Downloaded newer image for acockburn/appdaemon:3.0.5
Creating appdaemon ... done
Attaching to appdaemon
appdaemon    | Collecting ics (from -r /conf/requirements.txt (line 1))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/cf/68/e99b7c80638dd5dcc03e976ce2cb312e1a6abc8a6a7d688614bb62d61429/ics-0.6-py2.py3-none-any.whl (41kB)
appdaemon    | Collecting cryptography (from -r /conf/requirements.txt (line 2))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/ca/9a/7cece52c46546e214e10811b36b2da52ce1ea7fa203203a629b8dfadad53/cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl (2.3MB)
appdaemon    | Collecting PyJWT (from -r /conf/requirements.txt (line 3))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
appdaemon    | Collecting requests (from -r /conf/requirements.txt (line 4))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
appdaemon    | Collecting appdaemon (from -r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/f9/a1/83c3a95cc4e7dae04103f0f1115f17b5a98c8765d37e5f6c0c59ffb419c9/appdaemon-4.0.0-py3-none-any.whl (7.1MB)
appdaemon    | Collecting arrow (from -r /conf/requirements.txt (line 6))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/92/fa/f84896dede5decf284e6922134bf03fd26c90870bbf8015f4e8ee2a07bcc/arrow-0.15.5-py2.py3-none-any.whl (46kB)
appdaemon    | Collecting python-dateutil (from ics->-r /conf/requirements.txt (line 1))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
appdaemon    | Requirement already satisfied, skipping upgrade: six>1.5 in /usr/local/lib/python3.6/site-packages (from ics->-r /conf/requirements.txt (line 1)) (1.12.0)
appdaemon    | Collecting tatsu>4.2 (from ics->-r /conf/requirements.txt (line 1))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/1b/36/00664e684e4bba5730db661847447bbcfe789008a154755013e5f457b648/TatSu-4.4.0-py2.py3-none-any.whl (85kB)
appdaemon    | Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/site-packages (from cryptography->-r /conf/requirements.txt (line 2)) (1.12.3)
appdaemon    | Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->-r /conf/requirements.txt (line 4)) (2.8)
appdaemon    | Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->-r /conf/requirements.txt (line 4)) (3.0.4)
appdaemon    | Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->-r /conf/requirements.txt (line 4)) (2019.3.9)
appdaemon    | Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->-r /conf/requirements.txt (line 4)) (1.24.2)
appdaemon    | Requirement already satisfied, skipping upgrade: daemonize in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (2.5.0)
appdaemon    | Requirement already satisfied, skipping upgrade: voluptuous in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (0.11.5)
appdaemon    | Requirement already satisfied, skipping upgrade: pyyaml==5.1 in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (5.1)
appdaemon    | Collecting python-socketio (from appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/11/e0/71c90fbfc534108d0869ff5f92c16e4bc9b1347439b9022e815c03ff4193/python_socketio-4.4.0-py2.py3-none-any.whl (50kB)
appdaemon    | Requirement already satisfied, skipping upgrade: yarl==1.1.0 in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (1.1.0)
appdaemon    | Requirement already satisfied, skipping upgrade: paho-mqtt in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (1.4.0)
appdaemon    | Requirement already satisfied, skipping upgrade: astral in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (1.10.1)
appdaemon    | Requirement already satisfied, skipping upgrade: feedparser in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (5.2.1)
appdaemon    | Requirement already satisfied, skipping upgrade: Jinja2==2.10.1 in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (2.10.1)
appdaemon    | Requirement already satisfied, skipping upgrade: pytz in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (2019.1)
appdaemon    | Collecting bcrypt==3.1.4 (from appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/b8/09/905ec939994e2c49dcffff72f823802557f166b3815ea54c1db3671eed42/bcrypt-3.1.4-cp36-cp36m-manylinux1_x86_64.whl (54kB)
appdaemon    | Collecting deepdiff (from appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/19/0b/d5d8cc7c5773a88a33f47e02e46cc9a417e2d17a5930948b32c3deb09376/deepdiff-4.0.9-py3-none-any.whl (47kB)
appdaemon    | Requirement already satisfied, skipping upgrade: aiohttp-jinja2==0.15.0 in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (0.15.0)
appdaemon    | Collecting pid (from appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/82/bc/3633e94577c0f64864684be5a73251f194fd8673fb7c1f095597ef34dbc2/pid-2.2.5-py2.py3-none-any.whl
appdaemon    | Requirement already satisfied, skipping upgrade: websocket-client in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (0.56.0)
appdaemon    | Requirement already satisfied, skipping upgrade: iso8601 in /usr/local/lib/python3.6/site-packages (from appdaemon->-r /conf/requirements.txt (line 5)) (0.1.12)
appdaemon    | Collecting aiohttp==3.6.2 (from appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)
appdaemon    | Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->-r /conf/requirements.txt (line 2)) (2.19)
appdaemon    | Collecting python-engineio>=3.9.0 (from python-socketio->appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/97/16/66b05477d6057238e2fc1f8cfb1dfd0b3adad1351c30ad20934f09db5891/python_engineio-3.11.2-py2.py3-none-any.whl (49kB)
appdaemon    | Requirement already satisfied, skipping upgrade: multidict>=4.0 in /usr/local/lib/python3.6/site-packages (from yarl==1.1.0->appdaemon->-r /conf/requirements.txt (line 5)) (4.5.2)
appdaemon    | Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2==2.10.1->appdaemon->-r /conf/requirements.txt (line 5)) (1.1.1)
appdaemon    | Collecting ordered-set>=3.1.1 (from deepdiff->appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/a3/b7/d4d69641cbe707a45c23b190f2d717466ba5accc4c70b5f7a8a450387895/ordered-set-3.1.1.tar.gz
appdaemon    | Collecting jsonpickle>=1.0 (from deepdiff->appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/07/07/c157520a3ebd166c8c24c6ae0ecae7c3968eb4653ff0e5af369bb82f004d/jsonpickle-1.2-py2.py3-none-any.whl
appdaemon    | Collecting typing-extensions>=3.6.5; python_version < "3.7" (from aiohttp==3.6.2->appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/03/92/705fe8aca27678e01bbdd7738173b8e7df0088a2202c80352f664630d638/typing_extensions-3.7.4.1-py3-none-any.whl
appdaemon    | Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->appdaemon->-r /conf/requirements.txt (line 5)) (3.0.1)
appdaemon    | Collecting attrs>=17.3.0 (from aiohttp==3.6.2->appdaemon->-r /conf/requirements.txt (line 5))
appdaemon    |   Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
appdaemon    | Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from aiohttp==3.6.2->appdaemon->-r /conf/requirements.txt (line 5)) (1.1.0)
appdaemon    | Building wheels for collected packages: ordered-set
appdaemon    |   Building wheel for ordered-set (setup.py): started
appdaemon    |   Building wheel for ordered-set (setup.py): finished with status 'done'
appdaemon    |   Stored in directory: /root/.cache/pip/wheels/dd/70/f1/0a4953bd6d06e7dbffe8ef0197b558eaecb21fa6b043b50d73
appdaemon    | Successfully built ordered-set
appdaemon    | ERROR: ics 0.6 has requirement arrow<0.15,>=0.11, but you'll have arrow 0.15.5 which is incompatible.
appdaemon    | Installing collected packages: python-dateutil, arrow, tatsu, ics, cryptography, PyJWT, requests, python-engineio, python-socketio, bcrypt, ordered-set, jsonpickle, deepdiff, pid, typing-extensions, attrs, aiohttp, appdaemon
appdaemon    |   Found existing installation: requests 2.21.0
appdaemon    |     Uninstalling requests-2.21.0:
appdaemon    |       Successfully uninstalled requests-2.21.0
appdaemon    |   Found existing installation: bcrypt 3.1.6
appdaemon    |     Uninstalling bcrypt-3.1.6:
appdaemon    |       Successfully uninstalled bcrypt-3.1.6
appdaemon    |   Found existing installation: aiohttp 2.3.10
appdaemon    |     Uninstalling aiohttp-2.3.10:
appdaemon    |       Successfully uninstalled aiohttp-2.3.10
appdaemon    |   Found existing installation: appdaemon 3.0.5
appdaemon    |     Uninstalling appdaemon-3.0.5:
appdaemon    |       Successfully uninstalled appdaemon-3.0.5
appdaemon    | Successfully installed PyJWT-1.7.1 aiohttp-3.6.2 appdaemon-4.0.0 arrow-0.15.5 attrs-19.3.0 bcrypt-3.1.4 cryptography-2.8 deepdiff-4.0.9 ics-0.6 jsonpickle-1.2 ordered-set-3.1.1 pid-2.2.5 python-dateutil-2.8.1 python-engineio-3.11.2 python-socketio-4.4.0 requests-2.22.0 tatsu-4.4.0 typing-extensions-3.7.4.1
appdaemon    | WARNING: You are using pip version 19.1, however version 19.3.1 is available.
appdaemon    | You should consider upgrading via the 'pip install --upgrade pip' command.
appdaemon    | 2020-01-15 19:22:19.415038 INFO AppDaemon: AppDaemon Version 4.0.0 starting
appdaemon    | 2020-01-15 19:22:19.415196 INFO AppDaemon: Python version is 3.6.8
```

**Note the version of AD**

The rest of the startup was catastrophic:

````
appdaemon    | 2020-01-15 19:22:19.415284 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
appdaemon    | 2020-01-15 19:22:19.415367 INFO AppDaemon: Added log: AppDaemon
appdaemon    | 2020-01-15 19:22:19.415448 INFO AppDaemon: Added log: Error
appdaemon    | 2020-01-15 19:22:19.415528 INFO AppDaemon: Added log: Access
appdaemon    | 2020-01-15 19:22:19.415608 INFO AppDaemon: Added log: Diag
appdaemon    | 2020-01-15 19:22:19.432082 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
appdaemon    | 2020-01-15 19:22:19.460190 INFO HASS: HASS Plugin Initializing
appdaemon    | 2020-01-15 19:22:19.460344 INFO HASS: HASS Plugin initialization complete
appdaemon    | 2020-01-15 19:22:19.460517 INFO AppDaemon: Loading Plugin switches using class MqttPlugin from module mqttplugin
appdaemon    | 2020-01-15 19:22:19.464323 INFO switches: MQTT Plugin Initializing
appdaemon    | 2020-01-15 19:22:19.464483 INFO switches: Using 'appdaemon/status' as Will Topic
appdaemon    | 2020-01-15 19:22:19.464603 INFO switches: Using 'appdaemon/status' as Birth Topic
appdaemon    | 2020-01-15 19:22:19.465018 INFO AppDaemon: Loading Plugin dash using class MqttPlugin from module mqttplugin
appdaemon    | 2020-01-15 19:22:19.465163 INFO dash: MQTT Plugin Initializing
appdaemon    | 2020-01-15 19:22:19.465276 INFO dash: Using 'appdaemon-dash/status' as Will Topic
appdaemon    | 2020-01-15 19:22:19.465361 INFO dash: Using 'appdaemon-dash/status' as Birth Topic
appdaemon    | 2020-01-15 19:22:19.465757 INFO AppDaemon: HTTP is disabled
appdaemon    | 2020-01-15 19:22:19.494575 WARNING AppDaemon: Threads directive is deprecated apps - will be pinned. Use total_threads if you want to unpin your apps
appdaemon    | 2020-01-15 19:22:19.497260 INFO HASS: Connected to Home Assistant 0.103.4
appdaemon    | 2020-01-15 19:22:19.498740 INFO switches: Connected to Broker at URL mqtt.swtk.info:1883
appdaemon    | 2020-01-15 19:22:19.500247 INFO dash: Connected to Broker at URL mqtt.swtk.info:1883
appdaemon    | 2020-01-15 19:22:19.502253 INFO AppDaemon: Got initial state from namespace mqtt
appdaemon    | 2020-01-15 19:22:19.502528 INFO switches: MQTT Plugin initialization complete
appdaemon    | 2020-01-15 19:22:19.503818 INFO AppDaemon: Got initial state from namespace mqtt-dash
appdaemon    | 2020-01-15 19:22:19.504216 INFO dash: MQTT Plugin initialization complete
appdaemon    | 2020-01-15 19:22:19.537030 INFO AppDaemon: App 'GetState' added
appdaemon    | 2020-01-15 19:22:19.537249 INFO AppDaemon: App 'SendPluieDansHeureToMQTT' added
appdaemon    | 2020-01-15 19:22:19.537403 INFO AppDaemon: App 'hello_world' added
appdaemon    | 2020-01-15 19:22:19.537560 INFO AppDaemon: App 'MQTT' added
appdaemon    | 2020-01-15 19:22:19.537706 INFO AppDaemon: App 'WaterLeak' added
appdaemon    | 2020-01-15 19:22:19.537842 INFO AppDaemon: App 'MonitoringAlert' added
appdaemon    | 2020-01-15 19:22:19.537976 INFO AppDaemon: App 'TrackRide' added
appdaemon    | 2020-01-15 19:22:19.538126 INFO AppDaemon: App 'LightSwitch' added
appdaemon    | 2020-01-15 19:22:19.538270 INFO AppDaemon: App 'TimeBasedSwitch' added
appdaemon    | 2020-01-15 19:22:19.538399 INFO AppDaemon: App 'LightsMonitoring' added
appdaemon    | 2020-01-15 19:22:19.538560 INFO AppDaemon: App 'IFTTT' added
appdaemon    | 2020-01-15 19:22:19.538691 INFO AppDaemon: App 'internet-check' added
appdaemon    | 2020-01-15 19:22:19.538821 INFO AppDaemon: App 'netatmo' added
appdaemon    | 2020-01-15 19:22:19.538957 INFO AppDaemon: App 'meteo' added
appdaemon    | 2020-01-15 19:22:19.539089 INFO AppDaemon: App 'googlecalendar' added
appdaemon    | 2020-01-15 19:22:19.539216 INFO AppDaemon: App 'emploidutemps' added
appdaemon    | 2020-01-15 19:22:19.539355 INFO AppDaemon: App 'bushoche' added
appdaemon    | 2020-01-15 19:22:19.539491 INFO AppDaemon: App 'darkmode' added
appdaemon    | 2020-01-15 19:22:19.540561 INFO AppDaemon: Found 18 total apps
appdaemon    | 2020-01-15 19:22:19.540793 INFO AppDaemon: Starting Apps with 18 workers and 18 pins
appdaemon    | 2020-01-15 19:22:19.546415 INFO HASS: Evaluating startup conditions
appdaemon    | 2020-01-15 19:22:19.561478 INFO AppDaemon: Got initial state from namespace default
appdaemon    | 2020-01-15 19:22:21.547106 INFO AppDaemon: Scheduler running in realtime
appdaemon    | 2020-01-15 19:22:21.549487 INFO AppDaemon: Adding /conf/apps to module import path
appdaemon    | 2020-01-15 19:22:21.549934 INFO AppDaemon: Adding /conf/apps/dashboard to module import path
appdaemon    | 2020-01-15 19:22:21.570494 INFO AppDaemon: Loading App Module: /conf/apps/alerting.py
appdaemon    | 2020-01-15 19:22:21.577576 INFO AppDaemon: Loading App Module: /conf/apps/ifttt.py
appdaemon    | 2020-01-15 19:22:21.579365 WARNING AppDaemon: No app description found for: /conf/apps/news.py - ignoring
appdaemon    | 2020-01-15 19:22:21.580363 INFO AppDaemon: Loading App Module: /conf/apps/experiments.py
appdaemon    | 2020-01-15 19:22:21.585463 INFO AppDaemon: Loading App Module: /conf/apps/trackride.py
appdaemon    | 2020-01-15 19:22:21.603282 INFO AppDaemon: Loading App Module: /conf/apps/light.py
appdaemon    | 2020-01-15 19:22:21.605346 INFO AppDaemon: Loading App Module: /conf/apps/sendStateToMQTT.py
appdaemon    | 2020-01-15 19:22:21.606790 INFO AppDaemon: Loading App Module: /conf/apps/mqtt.py
appdaemon    | 2020-01-15 19:22:21.608893 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/netatmo.py
appdaemon    | 2020-01-15 19:22:21.628576 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/darkmode.py
appdaemon    | 2020-01-15 19:22:21.630205 WARNING AppDaemon: No app description found for: /conf/apps/dashboard/testmqtt.py - ignoring
appdaemon    | 2020-01-15 19:22:21.631093 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/emploi-du-temps.py
appdaemon    | 2020-01-15 19:22:22.143902 WARNING AppDaemon: No app description found for: /conf/apps/dashboard/dashboard.py - ignoring
appdaemon    | 2020-01-15 19:22:22.144497 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/bus-hoche.py
appdaemon    | 2020-01-15 19:22:22.145633 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/meteo.py
appdaemon    | 2020-01-15 19:22:22.147078 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/internet-check.py
appdaemon    | 2020-01-15 19:22:22.148312 INFO AppDaemon: Loading App Module: /conf/apps/dashboard/googlecalendar.py
appdaemon    | 2020-01-15 19:22:22.163451 INFO AppDaemon: Initializing app MQTT using class MQTT from module mqtt
appdaemon    | 2020-01-15 19:22:22.164374 WARNING MQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.165850 WARNING MQTT: Unexpected error initializing app: MQTT:
appdaemon    | 2020-01-15 19:22:22.166040 WARNING MQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.166780 WARNING MQTT: Traceback (most recent call last):
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
appdaemon    |     await self.init_object(app)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 280, in init_object
appdaemon    |     self.AD, name, self.AD.logging, app_args, self.AD.config, self.app_config, self.AD.global_vars
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/mqtt/mqttapi.py", line 63, in __init__
appdaemon    |     adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/adbase.py", line 75, in __init__
appdaemon    |     self.dashboard_dir = self.AD.http.dashboard_dir
appdaemon    | AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
appdaemon    |
appdaemon    | 2020-01-15 19:22:22.166920 WARNING MQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.167066 INFO AppDaemon: Initializing app GetState using class GetState from module experiments
appdaemon    | 2020-01-15 19:22:22.167757 WARNING GetState: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.167937 WARNING GetState: Unexpected error initializing app: GetState:
appdaemon    | 2020-01-15 19:22:22.168050 WARNING GetState: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.168485 WARNING GetState: Traceback (most recent call last):
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
appdaemon    |     await self.init_object(app)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 280, in init_object
appdaemon    |     self.AD, name, self.AD.logging, app_args, self.AD.config, self.app_config, self.AD.global_vars
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
appdaemon    |     adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/adbase.py", line 75, in __init__
appdaemon    |     self.dashboard_dir = self.AD.http.dashboard_dir
appdaemon    | AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
appdaemon    |
appdaemon    | 2020-01-15 19:22:22.168616 WARNING GetState: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.168745 INFO AppDaemon: Initializing app SendPluieDansHeureToMQTT using class PluieDansHeure from module sendStateToMQTT
appdaemon    | 2020-01-15 19:22:22.169732 WARNING SendPluieDansHeureToMQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.169928 WARNING SendPluieDansHeureToMQTT: Unexpected error initializing app: SendPluieDansHeureToMQTT:
appdaemon    | 2020-01-15 19:22:22.170050 WARNING SendPluieDansHeureToMQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.170276 WARNING SendPluieDansHeureToMQTT: Traceback (most recent call last):
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
appdaemon    |     await self.init_object(app)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 280, in init_object
appdaemon    |     self.AD, name, self.AD.logging, app_args, self.AD.config, self.app_config, self.AD.global_vars
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
appdaemon    |     adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/adbase.py", line 75, in __init__
appdaemon    |     self.dashboard_dir = self.AD.http.dashboard_dir
appdaemon    | AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
appdaemon    |
appdaemon    | 2020-01-15 19:22:22.170397 WARNING SendPluieDansHeureToMQTT: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.170519 INFO AppDaemon: Initializing app WaterLeak using class WaterLeak from module alerting
appdaemon    | 2020-01-15 19:22:22.171144 WARNING WaterLeak: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.171320 WARNING WaterLeak: Unexpected error initializing app: WaterLeak:
appdaemon    | 2020-01-15 19:22:22.171433 WARNING WaterLeak: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.171649 WARNING WaterLeak: Traceback (most recent call last):
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
appdaemon    |     await self.init_object(app)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/app_management.py", line 280, in init_object
appdaemon    |     self.AD, name, self.AD.logging, app_args, self.AD.config, self.app_config, self.AD.global_vars
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
appdaemon    |     adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
appdaemon    |   File "/usr/local/lib/python3.6/site-packages/appdaemon/adbase.py", line 75, in __init__
appdaemon    |     self.dashboard_dir = self.AD.http.dashboard_dir
appdaemon    | AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
appdaemon    |

(...) 

appdaemon    | 2020-01-15 19:22:22.191077 WARNING darkmode: ------------------------------------------------------------
appdaemon    | 2020-01-15 19:22:22.192230 WARNING AppDaemon: Unable to find module MQTT - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.192483 WARNING AppDaemon: Unable to find module GetState - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.192726 WARNING AppDaemon: Unable to find module SendPluieDansHeureToMQTT - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.193001 WARNING AppDaemon: Unable to find module WaterLeak - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.193243 WARNING AppDaemon: Unable to find module MonitoringAlert - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.193482 WARNING AppDaemon: Unable to find module TrackRide - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.193719 WARNING AppDaemon: Unable to find module LightSwitch - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.193957 WARNING AppDaemon: Unable to find module TimeBasedSwitch - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.194196 WARNING AppDaemon: Unable to find module LightsMonitoring - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.194534 WARNING AppDaemon: Unable to find module IFTTT - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.194775 WARNING AppDaemon: Unable to find module internet-check - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.195013 WARNING AppDaemon: Unable to find module netatmo - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.195249 WARNING AppDaemon: Unable to find module meteo - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.195484 WARNING AppDaemon: Unable to find module googlecalendar - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.195725 WARNING AppDaemon: Unable to find module emploidutemps - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.195960 WARNING AppDaemon: Unable to find module bushoche - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.196236 WARNING AppDaemon: Unable to find module darkmode - initialize() skipped
appdaemon    | 2020-01-15 19:22:22.196578 INFO AppDaemon: App initialization complete
```

Is the docker image fixable?

**Comment by ReneTode** [comment]
just use 4.0.0 and update the appdaemon.yaml, so that you are up to date.

**Comment by wsw70** [comment]
@ReneTode this is what I am doing right now (fortunately the changes are small, I will do a PR for some changes in the docs).

This said the fact that the `3.0.5` tag installs the version 4 is quite annoying for someone who wants to pull back quickly.

**Comment by ReneTode** [comment]
yeah, i understand. it is noted and ill as @acockburn  to look at it.

please discuss what you think is wrong in the docs first on our discord page before you make a PR.

**Comment by wsw70** [comment]
> please discuss what you think is wrong in the docs first on our discord page before you make a PR.

Yes I will. Some are typos (including some parameters), some are (what I believe to be) missing parts, some are unexpected changes in some functions (schedulers). i will take notes for all of that.

**Comment by ReneTode** [comment]
i can hardly think of any missing part, or unexpected changes, but ill be there to discuss it with you ;)
