### ISSUE TITLE
Issue in scheduler when launching a task on the same second

### ISSUE THREAD

**Issue by wogri** [AppDaemon/appdaemon#913]
Take the following example: 

```python
time = datetime.time(7, 1, 33)
self.run_minutely(self.check_update_favourites, time)
```

If appdaemon is started in exactly this second (second 33) of the minute, the task can not be initialized: 

```
2020-03-05 09:14:33.535264 WARNING music_kueche_touchpanel: Traceback (most recent call last):                                                               
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/app_management.py", line 145, in initialize_app                                                     
    await utils.run_in_executor(self, init)                                                                                                                  
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/utils.py", line 276, in run_in_executor                                                             
    response = future.result()                                                                                                                               
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run                                                                                    
    result = self.fn(*self.args, **self.kwargs)                                                                                                              
  File "/appdaemon/config/apps/sonos.py", line 87, in initialize                                                                                             
    self.run_minutely(self.check_update_favourites, time)                                                                                                    
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper                                                          
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))                                                                                          
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe                                                    
    result = future.result(self.AD.internal_function_timeout)                                                                                                
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result                                    
    return self.__get_result()                                                                                           
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result                                                                          
    raise self._exception                                                                                                         
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/adapi.py", line 2433, in run_minutely                                                              
    handle = await self.run_every(callback, event, 60, **kwargs)                                                                      
  File "/appdaemon/lib/python3.7/site-packages/appdaemon/adapi.py", line 2476, in run_every                                                                 
    raise ValueError("start cannot be in the past")                                                      
ValueError: start cannot be in the past                                                                                                                     
```

It seems that there is a bug in the [convert_naive function](https://github.com/home-assistant/appdaemon/blob/0ed2b275463d1039156d543139253a820d4471f3/appdaemon/scheduler.py#L740) in scheduler.py that leads to unexpected behavior. By quickly glancing at it I didn't really understand the code. 

This is new behavior in appdaemon 4.0.x, didn't happen to me in appdaemon 3.

**Comment by acockburn** [comment]
In your example above, 7:01:03 is very definitely in the past, and that was never allowed with this particular call - if it got through somehow it was a bug ;) If you do want to run every minute at 33 seconds past the minute, the best way is to grab a current datetime object and substitute the minute for the current minute +1 and the seconds for 33. If you don't care about the exact second past the hour, the next version (4.0.4) will allow you to use the keyword "now" instead of a datetime and will start the clock running from that point onward.

**Comment by ReneTode** [comment]
from the docs:
> start – A Python time object that specifies when the callback will occur, the hour and minute components of the time object are ignored. If the time specified is in the past, the callback will occur the next minute at the specified time.

only run_every didnt allow past starttime.

**Comment by acockburn** [comment]
Ahh yes, good point Rene - thanks. I'll take a deeper look at this.

**Comment by ReneTode** [comment]
but it might have been something that was already there before, and nobady really noticed, because the app needs to be initialised at exactly that point and run_minutely isnt used that much.

**Comment by wogri** [comment]
I’m pretty confident it wasn’t there before. Since the upgrade to 4.0.x it
already happened twice to me and I haven’t seen this error the 2 years I
used appdaemon before.

**Comment by ReneTode** [comment]
timing is different in AD 4.
for example run_every in most cases accepted datetime.now() as starttime, but AD 4 takes a few microseconds more to start a callback, and now now is always in the past.

this could be simular, it could have been there all along, but now it shows itself more.

**Comment by wogri** [comment]
Any updates on this?

**Comment by ReneTode** [comment]
i got quite a few run_every's and still havent had that error.
but if you got it still, i would place a check in front of the run_every line. (at least for now)

**Comment by wogri** [comment]
It's not happening in the run_every's, but in the run_minutely calls. But I guess changing this to run_every with a few seconds in the future of `now` is a simple enough fix.
