### ISSUE TITLE
Callback Locking issues

### ISSUE THREAD

**Issue by Odianosen25** [AppDaemon/appdaemon#920]
In the latest dev we got some issues, that had to do with the dict not being locked during access

```
2020-03-06 10:37:13.722184 WARNING AppDaemon: ------------------------------------------------------------
2020-03-06 10:37:13.723215 WARNING AppDaemon: Unexpected error during 'process_event()'
2020-03-06 10:37:13.724691 WARNING AppDaemon: ------------------------------------------------------------
2020-03-06 10:37:13.725919 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/stream/adstream.py", line 64, in process_event
    for handler in self.handlers:
RuntimeError: dictionary changed size during iteration

2020-03-06 10:37:13.726862 WARNING AppDaemon: ------------------------------------------------------------
```

and 
```
2020-03-06 09:30:45.700947 WARNING AppDaemon: ------------------------------------------------------------
2020-03-06 09:30:45.701188 WARNING AppDaemon: Unexpected error during process_event()
2020-03-06 09:30:45.701392 WARNING AppDaemon: ------------------------------------------------------------
2020-03-06 09:30:45.701956 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/events.py", line 195, in process_event
    await self.AD.state.process_state_callbacks(namespace, data)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 206, in process_state_callbacks
    for name in self.AD.callbacks.callbacks.keys():
RuntimeError: dictionary changed size during iteration

2020-03-06 09:30:45.702159 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by ReneTode** [comment]
can it be that the removal from some deepcopy's has to do with these errors?

**Comment by Odianosen25** [comment]
@ReneTode nice to hear from you again :) . It not exactly that really, I am if the view it’s the way we lock it and maybe we should change strategy. We use thread.RLock, and I think we should use asyncio.Lock instead. @acockburn said he will look into it later when he has some time, that for now I should leave it here to remind him.

**Comment by ReneTode** [comment]
ok. ill watch if i see a pr that takes care of it so that i also can use it.

i thought about it because i noticed that its possible to change app settings (again)

i got an app that uses this:
```
            devices =self.app_config["settings"]["alexa_groups"]["default"]
            for device in devices:
                 if device == "something":
                    devices.remove(device)
```
in the past that gave trouble and we added some deepcopy in AD.
in the dev version i use (from 25-2) this gives trouble again.
the app settings are changed, and dont recover untill i restart AD, so i need to deepcopy app_config.

i thought it might be related, but i guess thats another issue.

**Comment by ReneTode** [comment]
tonight i got the error again, and i noticed that it happened at the same time as when an HA service call took longer.

```
2020-03-09 21:11:47.506798 WARNING AppDaemon: ------------------------------------------------------------
2020-03-09 21:11:47.507391 WARNING AppDaemon: Unexpected error during 'process_event()'
2020-03-09 21:11:47.507895 WARNING AppDaemon: ------------------------------------------------------------
2020-03-09 21:11:47.508690 WARNING AppDaemon: Traceback (most recent call last):
  File "/mnt/usbdrive/pi/ADvenvdev250220/lib/python3.6/site-packages/appdaemon/stream/adstream.py", line 64, in process_event
    for handler in self.handlers:
RuntimeError: dictionary changed size during iteration

2020-03-09 21:11:47.509225 WARNING AppDaemon: ------------------------------------------------------------
```

```
09-03-2020 21:11:42;verw_HK_haard_main_app;verw woonkamer;on;heating
```
and for that app i got regular:
```
2020-03-09 21:27:50.155635 WARNING AppDaemon: callback temp_change() in verw_HK_haard_main_app has now completed
```
